### ISSUE TITLE
igNumericEditor display value is not cleared after value is set to null

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/ignite-ui#1025]
### Description  
igNumericEditor display value is not cleared after value is set to null

### Steps to reproduce  
1. Run the following code:
```
$("#editor").igNumericEditor({
	"allowNullValue": true,
	"nullValue": null,
	"revertIfNotValid": false
});
```
2. Type a value, e.g. 10.
3. Dynamically set value to null.

```
$("#editor").igNumericEditor("value", null)
```

### Result  
Even the value is set to null and if you get the display value using the dispalyValue method it is empty, still 10 is shown in the editor

### Expected result  
The editor should be empty.

**Comment by IG-Stanimir-Dimitrov** [comment]
Issue closed with https://github.com/IgniteUI/ignite-ui/pull/1026
