### ISSUE TITLE
Exception is thrown if "nullValue" is set to a number in the MaskEditor

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#1027]
### Description  
"Uncaught TypeError: Cannot read property 'length' of undefined" is thrown if you try to type inside a mask editor that has "nullValue" option's value set to a number.

### Steps to reproduce  

1. `$("#editor").igMaskEditor({ allowNullValue: true, nullValue: "0" });`
2. Click inside the editor
3. Type "abc"

### Result  
Exceptions are thrown:
infragistics.ui.editors.js:26   Uncaught TypeError: Cannot read property 'length' of undefined

### Expected result  
The editor is rendered with "0_____" dispalyed inside.
No exceptions are thrown when typing

**Comment by damyanpetev** [comment]
The actual problem is incorrect initialization when the `value` or `nullValue` are not valid. The same behavior can also be reproduced with:
```js
.igMaskEditor({ 
  inputMask : "9900",
  value: "abc" //should be numerics
});
```
