### ISSUE TITLE
how to add this to asp.net application in VS 2013?

### ISSUE THREAD

**Issue by F-Makhokha** [IgniteUI/ignite-ui#1032]
### Description  
I would like to ask how to add this feature to my VS 2013 project

**Comment by kdinev** [comment]
The easiest way to include Ignite UI in your VS2014 project (assuming it's MVC) is to install the NuGet package:

https://www.nuget.org/packages/IgniteUI/

**Comment by F-Makhokha** [comment]
Thanks I did that, and installed perfectly.

However I thought this install is not trial version when I run my application, is showing trial version on the bottom right coner. I guess this library might not be helpful for me.

Does anyone knows if there is complete free Open source with similar features?
Thanks.

**Comment by kdinev** [comment]
@F-Makhokha The OSS version doesn't contain an MVC extension assembly and is not available on NuGet. We should probably create a package for that as well. For now there is an NPM and Bower packages available for the OSS version, so if you're doing a ASP.NET Core application, you can directly

`npm install ignite-ui`

or 

`bower install ignite-ui`

From your project. If not, then open a terminal at your project folder and do one of the above.

**Comment by kdinev** [comment]
@F-Makhokha Did you manage to get it installed properly in your project? Should I close the issue?

**Comment by F-Makhokha** [comment]
We can close the issue thanks
