### ISSUE TITLE
maxLength option is not respected on Android devices

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#1043]
### Description  
When an igTextEditor  with 'maxLength' option set is opened on Android device, the 'maxLength' option is not respected and entering more symbols is allowed.

### Steps to reproduce  

1. `$("#editor").igTextEditor({ maxLength: 5 });`
2. Open the sample on Android device
3. Enter '12345678' in the editor

### Result  
'12345678' is allowed and the value is preserved after blurring the editor

### Expected result  
Only 5 symbols are allowed. Value is '12345'

**Comment by damyanpetev** [comment]
After looking into this I see a few issues:
- We normally cancel `keydown` or `keypress` to prevent wrong input but that is not respected while composing. Further, new specs deprecate `keypress` and some browsers on mobile have removed it already. Composition itself is also supposed to not require key events and Firefox has removed those entirely (though they plan to restore them for I believe).
  Yet I see no browser with `beforeInput` implemented, so until [UI Events](https://w3c.github.io/uievents/) are finalized and implemented we are sort of stuck on controlling composition input (most of mobile).
- The auto-complete on software keyboards is also supposed to be a version of "composition" but currently only FireFox fires those events, while Chrome on Android does not.

So the way we can go while waiting on spec/browser updates:
- Have composition ending properly trim the value - usually that means if the user is in the middle of composing composing a longer word it will be allowed to finish but it will get cut after, similar to paste. This actually matches the native `maxlength` attribute.
- Might need the general value processing to also trim for the second case so the editor ends up valid in the end. This will however cause a slight change in the `value()` method which currently won't trim, but reject the long text entirely.

**Comment by damyanpetev** [comment]
Actually just noticed the last part about `value()` applying a trim was already added for #1042 so no further change in this case.
