### ISSUE TITLE
Add a new igTimePicker control

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#1083]
Create a new component igTimePicker by extending the date editor and adding a dropdown list widget with 24h period split into 30min time intervals.

**Comment by NishantThakkar** [comment]
Any update on the same?

**Comment by SlavUI** [comment]
This will be introduced in Sprint 4

**Comment by bkulov** [comment]
Closing this issue as it's already done. Only MVC wrappers are pending #1563.
