### ISSUE TITLE
Review and update all controls code for event argument comments 

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#1089]
The Ignite UI API is generated by a parsing engine looking for particular arguments. Therefore, all control event comments must be compliant with the guidelines as defined in the repo wiki https://github.com/IgniteUI/ignite-ui/wiki/API-Documentation-Guidelines#events.

Review control source and fix any issues with the event arguments.
- [x] Editors #1484 
- [x] Rating #1485 
- [x] Dialog #1486
- [x] VideoPlayer #1488

**Comment by kdinev** [comment]
@bazal4o @mpavlinov @zdrawku Is there controls that are still not documented according to the documentation guidelines?

**Comment by mpavlinov** [comment]
@kdinev From my side only Pivot related controls are not updated.

**Comment by zdrawku** [comment]
Except igGridExcelExporter, I can verify that all controls owned by Phoenix team are following the documentation guidelines, this includes igScheduler as well.

For the igGridExcelExporter TFS work item has been created in order to Review the control source and fix any inconsistencies.

**Comment by bazal4o** [comment]
For PwnJS the following components from the ownership are not completed: 
igSpakline - Not Completed
igDialog - Not Completed
Editors - In Progress
igRating - Not Completed
igVideoPlayer - Not Completed

**Comment by zdrawku** [comment]
igExcelExporter changes are ready - PR 2592: Fixing incosistenncies in igGridExcelExporter documentation

**Comment by bazal4o** [comment]
Yes we are done. Sorry for the delay in the response.
