### ISSUE TITLE
In igTree there is no checkbox state binding

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/ignite-ui#1130]
### Description  
I want to have the functionality to load the checkbox state from the data source.

### Steps to reproduce  

I need a new binding option "checkedKey".

**Comment by kdinev** [comment]
@mpavlinov I suppose the same should be exposed for the expanded state of parent nodes?

**Comment by kdinev** [comment]
@mpavlinov Could you tell me what you think the behavior should be if there is a `checkboxMode: "tristate"` and topmost parent having a `__checked__` property being `true`, which `checkedKey` in `bindings` being `__checked__`, but no child data node having a `__checked__` property?

**Comment by mpavlinov** [comment]
@kdinev Should inherit the parent value if it doesn't have own property present.

**Comment by kdinev** [comment]
My initial design is to include `expandedKey` and `checkedKey` into the `bindings` object. The values of the keys would be used for tracking the expanded and checked states of each node through its data object.  

Example new `bindings` object:  

```
bindings: {
    textKey: "text",
    valueKey: "value",
    expandedKey: "__expanded__",
    checkedKey: "__checked__",
    childDataProperty: "children"
}
```

The default value for `expandedKey` would be `__expanded__`, and for `checkedKey` would be `__checked__` to minimize the chances for collision with keys already existing in the data that serve another purpose. 

Keys in the data would be of type `Boolean` for `expandedKey` and of type string for `checkedKey` to support tristate enumeration for `checkboxMode: "triState"`. The current `checkState()` API returns a string enumeration: 

```
var checkedState = $("treeID").igTree("checkedState", node); 
// "on" - checked, "off" - unchecked, "partial" - partially checked
```

All states for `expanded` and `checked` would be removed from DOM attributes and tracked entirely through the data objects of the nodes.

@mpavlinov @IG-Stanimir-Dimitrov Could you please review?

**Comment by mpavlinov** [comment]
@kdinev There is already an [expandedKey](https://www.igniteui.com/help/api/2017.1/ui.igtree#options:bindings.expandedKey) API. For the checkedKey I'm good with the proposal.

**Comment by kdinev** [comment]
@mpavlinov The `expandedKey` is currently used only for initial rendering and is not even documented properly for usage. I intend to expand its functionality to the same as the `checkedKey` that I'm going to implement, and make it two-way.

**Comment by mpavlinov** [comment]
@kdinev I'm good with the proposed changes.

**Comment by IG-Stanimir-Dimitrov** [comment]
I am ok with the changes. 
The only concern I have is that the current `expandedKey` default value is `Expanded` so will need also to take that as input for clients who are migrating to 17.2

**Comment by kdinev** [comment]
@IG-Stanimir-Dimitrov This should not be an issue. This key was never documented for usage and it was never two-way. Even if they use it with value "Expanded", they can just define the same value in bindings.

**Comment by kdinev** [comment]
@mpavlinov @IG-Stanimir-Dimitrov I'm moving forward with development, since both of you are OK with the proposed changes.
