### ISSUE TITLE
IgScroll custom scrollbar thumb gets too small when the scroll container has big height

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/ignite-ui#1135]
[defaultTable-igScroll.zip](https://github.com/IgniteUI/ignite-ui/files/1231459/defaultTable-igScroll.zip)

### Steps to reproduce  

1. Open the attached sample
2. Hover over the vertical scrollbar

### Result  
The vertical scroll thumb is very small

### Expected result  
There should be min height of the vertical scroll thumb. Same with the horizontal one.

**Comment by gmurray81** [comment]
Was someone going to look at this? Was trying to use igScroll in a prototype and was bitten by this. Seems like it would be easy enough to inject a minimum size.

**Comment by kdinev** [comment]
@gmurray81 We will get this fixed.
