### ISSUE TITLE
Not able to have two filtering conditions into igCombo

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/ignite-ui#1148]
### Description  
By specification, you have to be able to declare two filtering type conditions simultaneously

> contains + starts with (filter all items that contains a text that starts with the input text)

### Result  
You are not able to declare two filtering type conditions.

### Expected result  
You have to be able to declare through two filtering type conditions.
The possible declarations could be:
1. contains + starts with
2. starts with + ends with
3. contains + ends with
4. contains + contains.

**Comment by IG-Stanimir-Dimitrov** [comment]
Implementation details:

- Implement a new public method `filterByExpressions` that is the main igComo filtering method.
- If the developer sets a string or an array through the existing `filter` method, it must apply its current behavior. 
- If an array of objects is passed in through the existing `filter` method, it calls  `filterByExpressions() `

```
$(".combo").igCombo("filterByExpressions ", ([
    {expr: "Smith", cond: "contains", logic: "OR"},
    {expr: "Mary", cond: "endsWith"}
]));

```
