### ISSUE TITLE
Remove $.ig.setRegionalDefault from infragistics.util.jquery.js

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#1151]
### Description  
Remove `$.ig.setRegionalDefault` from `infragistics.util.jquery.js` since the locale/regional setting is now set in `infragistics.ui.widget.js `

**Comment by Lipata** [comment]
Remove $.ig.setRegionalDefault method, but keep the functionality that sets regional.defaults to the last included regional file. This will not introduce a breaking change and most importantly in cases, where you want to include only one regional file (JA for example), different from the default English one, then all the controls will get the JP regional settings, and no additional configuration will be needed.
