### ISSUE TITLE
infragistics.lob-lite.js file has incorrect regex asci characters

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/ignite-ui#116]
When using igMaskEditor/igDateEditor and initial value is set the following error occurs: (See the screenshot)

![image](https://cloud.githubusercontent.com/assets/4228115/16920266/a38dbbfa-4d15-11e6-97a5-f9c20e8c3b9a.png)

**Comment by damyanpetev** [comment]
Discovered it also affects stuff in util, so this applies to core file as well. 

Related issue is UglifyJS2/54 and the suggested approach is to set ascii_only, which does help. However, it does encode characters in the localization files and the current config uses Uglify to simultaneously combine and minify files. Therefore, the current setup will have to change with specific options for minification and separate combine (concat?) module doing the bundling.
