### ISSUE TITLE
Base Widget default language and regional

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/ignite-ui#1165]
#### Regional
This started out with me wanting to null the default `regional` in the base widget as regional of `"en-US"` only ever works if you explicitly include that regional file. For every other occasion the `$.ig.regional.defaults` is in effect and that can change based on the last file - e.g. like the common use of including Japanese regional that'll apply correctly to all widgets despite the option being set to EN.

#### Language
As is with all consistent features, locale behaves differently. The first locale to register sets the defaults, however builds also come bundled with either "en" or "ja", so the EN build will always be able to find that "en" locale no matter the defaults. 

That last bit might sound insignificant, but I remembered we only have EN build versions for CDN so plenty of localized apps and samples using the CDN links rely on including the locale before anything else so the desired locale is applied. We use this for Fiddle from samples and the ones embedded in the help, but I'm guessing some applications in the wild might rely on that behavior too.

Case in point: https://jsfiddle.net/gh/get/jquery/1.9.1/IgniteUI/help-samples/tree/master/17.1/JA/grid/grid-api-events/fiddle
This grid sample with the latest changes would end up with a mix of EN locale and JA regional
So a <kbd >bug</kbd> maybe?

I tried removing the default language, but there's also a `$.ig.util.language = "en";` in util that kicks in as a fallback that should also be removed and logic adjusted.

// tagging people @IG-Stanimir-Dimitrov @kdinev @mpavlinov @bazal4o @Lipata

**Comment by kdinev** [comment]
The mechanism of the locale, which is also how the regional should function, is:

1. Locale is extracted with a fallback. 
1.1. First a `locale` object specific to the control is checked for the key.
1.2. Then the check falls back to the global `locale` file with the specified `language`. If no language is defined the default is used.
1.3. Then the check falls back to the global `locale` file that is loaded, regardless of what the `language` option value is.

Result:
1. If control instance specific locale is provided, the key is extracted from it.
2. If no control instance specific locale is provided.
2.1. If a `language` is provided and the language file is loaded, then the key from that language file is loaded.
2.2. If a `language` is not provided, and English language file is loaded (English is default), then the key is loaded from the English file.
2.3. If a `language` is not provided, and English language file is not loaded, but instead another language file is loaded, then the other language file has populated the language independent locale and the key is loaded from the language file.

**Comment by kdinev** [comment]
@damyanpetev Should I close this issue? There's no comments on my response since September 20th.
