### ISSUE TITLE
Limitation in the knockoutjs bindingHandler igEditorDisable

### ISSUE THREAD

**Issue by seawerst** [IgniteUI/ignite-ui#1168]
The function should not limit his usability to an observable.
If in the databind markup we wish to use a custom test:
data-bind="igEditorDisable : mode() !== 1"
where mode is an observable number, the function just return. Instead you should use 
ko.utils.unwrapObservable or the shortcut ko.unwrap on the valueAccessor.

**Comment by Lipata** [comment]
Thank you @seawerst for the good recommendation! Now this is implemented in our KO handlers for the editors.

**Comment by seawerst** [comment]
It's a pleasure.
