### ISSUE TITLE
knockoutjs issue with requirejs amd module

### ISSUE THREAD

**Issue by seawerst** [IgniteUI/ignite-ui#1179]
In your knockout extensions, you define a dependency on knockout but it's not passed to the definition function as function argument. Instead you only enter a comment `/*global ko*/`. How do you manage to have ko globally defined when knockout also `define(...` when it detect requirejs so it's no longer in global.

You should probably use something like:
`(function (factory) {
	if (typeof define === "function" && define.amd) {
		define( [
            "jquery",
            "knockout",
            "jquery-ui",
            "../modules/infragistics.util",
			"../modules/infragistics.util.jquery",
			"../modules/infragistics.util.jquerydeferred",
            "../modules/infragistics.ui.editors"
            ], factory );
	} else {
		factory(jQuery, ko);
	}
}
(function ($, ko) {
	function updatePrope`

![image](https://user-images.githubusercontent.com/5280138/30170825-281f4aba-93be-11e7-84db-1b18c3befcb9.png)

Notice the ordre of the dependencies and the additional function parameters.

**Comment by Lipata** [comment]
@seawerst thank you! Just FYI the  `/*global ko*/` is related to the JSHint validation for our code and it says that `ko` is globally defined.
