### ISSUE TITLE
igDatePicker does not change its regional when initialized without options

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/ignite-ui#1180]
### Description  
Init an igDatePicker with no options - `$("#dp").igDatePicker();`

### Steps to reproduce  

1. Change its regional option: `$("#dp").igDatePicker("option", "regional", "ja");`

### Result  
It does not change the regional settings

### Expected result  
igDatePicker should apply its new regional settings when initialized without options

**Comment by IG-Stanimir-Dimitrov** [comment]
@Lipata , can you please look at this for Sprint 8  :)
