### ISSUE TITLE
igCombo filtered event is fired, even if filtering event is cancelled

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/ignite-ui#1183]
igCombo filtered event is fired, even if filtering event is cancelled

### Steps to reproduce  

1. Enter some value in the combo inbox to trigger filtering

### Result  
filtered event is fired

### Expected result  
filtered event is not fired, because filtering event returns false
[combo.zip](https://github.com/IgniteUI/ignite-ui/files/1296102/combo.zip)

**Comment by kdinev** [comment]
@hanastasov Please put severity and versions.
