### ISSUE TITLE
igCombo filters its items when loading next chunk of data

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/ignite-ui#1184]
### Description  
igCombo filters its items when loading next chunk of data

### Steps to reproduce  

1. Type "s" in the combo input to trigger filtering
2. Select the first item from the matching items
3. Open the dropdown
4. Scroll down to see more items

### Result  
Filtering is executed and now we see only the initially selected item in the list of matching items

### Expected result  
No filtering to be executed
[combo.zip](https://github.com/IgniteUI/ignite-ui/files/1296150/combo.zip)

**Comment by kdinev** [comment]
@hanastasov please put severity and versions.
