### ISSUE TITLE
Combined regional file doesn't contain datepicker settings

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/ignite-ui#1186]
### Description  
The current version of the [infragistics.ui.regional-i18n.js](https://github.com/IgniteUI/ignite-ui/blob/9b45d041015713b22c7c36b311c18cab4795cc15/src/js/modules/i18n/regional/infragistics.ui.regional-i18n.js) combined regional file doesn't contain `$.datepicker` settings unlike the per-regional files.
This prevents controls relying on the picker from properly applying regional options.

**Comment by damyanpetev** [comment]
@kdinev There's a slightly obscure note under ["The jquery-ui-i18n.js must be referenced on the page."](https://www.igniteui.com/help/deployment-guide-javascript-resources#referencing_localization_resources), though I have a slight suspicion that might predate the datepicker options in the split files. Thus the question label.

**Comment by kdinev** [comment]
No, the file should not contain jQuery UI specific resources.

**Comment by damyanpetev** [comment]
Fair enough :)
