### ISSUE TITLE
Only one style can be selected in IЕ in igHtmlEditor

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/ignite-ui#1189]
### Description  
Only one style can be selected in IЕ in igHtmlEditor

### Steps to reproduce  

1) Run the attached sample
2)Try to select more than one style(for example Bold, Italics and Underline)

### Result  
Only the last selection(last command to browser is excuted) is applied. If you have selcted Bold, for example, and click Italics, only Italics style is applied.

### Expected result  
Expected result is to apply all selected styles.
[htmlEditor.zip](https://github.com/IgniteUI/ignite-ui/files/1298764/htmlEditor.zip)

**Comment by rkaraivanov** [comment]
@kdinev @hanastasov 

After testing the provided sample with the latest builds in `16.2`, `17.1` and `master` I cannot reproduce the reported issue.
