### ISSUE TITLE
[igDialog] openAnimation prevents modal background from appearing

### ISSUE THREAD

**Issue by mharrington622** [IgniteUI/ignite-ui#1204]
### Description  
When modal is true and openAnimation is being used, the modal background does not appear until the dialog receives focus, allowing users to interact with the background still.

### Steps to reproduce  

1. Run [attached sample](https://github.com/IgniteUI/ignite-ui/files/1315144/igDialog_ModalBackground.zip)
2. Click "Test" button
3. After the dialog opens, try to highlight the text outside the dialog.

### Result  
You can still interact with the page.

### Expected result  
You should not be able to interact with the page.

### Notes
Does not occur in 16.2.20162.2040

**Comment by kdinev** [comment]
@mharrington622 Does it occur in 16.2 at all?

**Comment by mharrington622** [comment]
@kdinev  Yes, I can reproduce in current version, 16.2.20162.2208

**Comment by kdinev** [comment]
@mharrington622 A fix is expected in `version: 17.1`, correct? Because we just released the last SR for `version: 16.2`.

**Comment by mharrington622** [comment]
@kdinev It was never mentioned since it was posted on the forums.  The customer mentioned it was not a critical feature for them and they have a workaround.

**Comment by SlavUI** [comment]
@mharrington622  and @kdinev can we close this issue is it resolved :)

**Comment by kdinev** [comment]
We're using this issue as an example in the training this week. A fix will be PRed by @Lipata

**Comment by Lipata** [comment]
@kdinev this is not the same bug, the one used for the training is #1391. I have added the 18.1 label, and @SlavUI we will need to work on it.
