### ISSUE TITLE
[igScheduler] Buttons padding is missing

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/ignite-ui#1256]
### Description  
When open the Dialog for appointmet editing or the popover for appoinment action, the buttons do not have paddings.
![paddingissue](https://user-images.githubusercontent.com/11193764/31131348-93f2e00e-a862-11e7-9b53-ed05af012867.PNG)

**Comment by desig9stein** [comment]
@zdrawku, please review that with latest changes

**Comment by zdrawku** [comment]
Working like a charm
