### ISSUE TITLE
Modal dialogs in bootstrap3 theme are broken.

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/ignite-ui#1265]
### Description  
Modal dialogs in bootstrap3 theme are broken.

### Steps to reproduce  

1. Open [http://jsfiddle.net/dkamburov/xepcrkyp/](http://jsfiddle.net/dkamburov/xepcrkyp/)
2. Click **select columns** to open group by dialog

### Result  
![image](https://user-images.githubusercontent.com/1182001/31173498-732733a8-a910-11e7-8c10-069f6184e4e6.png)

### Expected result  
The dialog should look correct

**Comment by kdinev** [comment]
Apart from the issue described, the arrow buttons inside the dialog, as well as the close button should not have borders.

**Comment by ChronosSF** [comment]
@kdinev, @desig9stein  - Before logging a separate issue, is it expected that in the 17.2 the header of the dialog to be blue while it was gray in 17.1 . The hover styles of the buttons are also colored blue when they were dark grey before.  (talking about the bootstrap4/default theme, but it seems to be applicable to bootstrap3 too)

**Comment by desig9stein** [comment]
So far all our themes didn't make use of the variables as they should do. each theme has a brand color which should be the main color for the theme. It is normal the action buttons to be colored in that color. I can bring back the old color but then what's the point each team to have "@brind-primary", "@accent" colors if they don't use it?
