### ISSUE TITLE
Hovering items from moving dialog is hides the text in bootstrap themes(flatly too)

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/ignite-ui#1268]
### Description  
Hover over the up and down arrows of the moving dialog, makes the text to disappear

### Steps to reproduce  

1. Open [http://jsfiddle.net/dkamburov/kdco9aLk/](http://jsfiddle.net/dkamburov/kdco9aLk/)
2. Open moving dialog
3. Hover an arrow

### Result  

![image](https://user-images.githubusercontent.com/1182001/31176826-de23fe8c-a91c-11e7-9b18-061e813e2228.png)

### Expected result  
Header text should be visible when trying to click the arrows

**Comment by desig9stein** [comment]
The example, that you provide, is not with the latest code. The dialog for group by is broken but I already fix that. please provide a JSfiddle with the latest changes.

**Comment by dkamburov** [comment]
There you go - [http://jsfiddle.net/dkamburov/kdco9aLk/2/](http://jsfiddle.net/dkamburov/kdco9aLk/2/)

It is the moving dialog, not the group by one, hover style is white and hides the text
