### ISSUE TITLE
Using the Superhero theme applies background color to the body of the page.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/ignite-ui#1272]
### Description  
The Superhero theme applies background color to the HTML body of the page.

### Steps to reproduce  

1. Open http://jsfiddle.net/n1q9mtpb/
2. Observe the background of the grid's page viewer

### Result  
![background](https://user-images.githubusercontent.com/3768136/31183362-04c43b12-a92f-11e7-8f2c-2b37bc1cfe9a.jpg)

### Expected result  
The background shouldn't be affected visually by the Superhero theme

**Comment by desig9stein** [comment]
We take that theme form:
https://bootswatch.com/superhero/
There the background is in the dark color, so I change it. All our themes have variable called "body-bg" so far they just don't use it, so I added it

I think that if the user uses that theme he will expect the background color to be dark.

**Comment by mpavlinov** [comment]
@desig9stein Just make it work as in 17.1 please!
