### ISSUE TITLE
Feature Chooser icons not visible when hovering over them in Superhero theme

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/ignite-ui#1286]
### Description  
Hovering over the feature chooser fields makes the backgroun-color to white, but the icons being grey are barely visible then.

### Steps to reproduce  

1. Open http://jsfiddle.net/4L547wh6/
2. Click on the gear icon of the feature chooser
3. Hover over some field

### Result  
![feature_icons](https://user-images.githubusercontent.com/3768136/31226085-889a83e8-a9dd-11e7-980b-80a3c56856c5.jpg)

### Expected result  
Maybe the hover color only for the feature chooser could be orange instead? That way the icons could still be the same.

I am not sure but maybe something is hiding the icons, because in other themes they are visible on white background.

**Comment by desig9stein** [comment]
@skrustev, please review that with latest changes.

**Comment by skrustev** [comment]
It looks like it is fixed with the latest changes. Closing this issue.
