### ISSUE TITLE
Options in datepicker's dropdowns are not visible when using "bootstrap 3.3.7"

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#1371]
### Description  
When using "bootstrap 3.3.7" the options inside the "changeYear" and "changeMonth" dropdowns are not visible when not hovered. Additionally, the value inside the date picker disappears when hovered. 

### Steps to reproduce  

1. Run the attached sample
[sample.zip](https://github.com/IgniteUI/ignite-ui/files/1449263/sample.zip)

2. Select a date and hover the editor
3.Show the calendar
4. Open the "changeYear" dropdown

### Result  
Step 2 -> The selected date disappears when hovered
Step 4 -> The years in the list are not visible unless hovered (See the attached screenshot)
![screenshot](https://user-images.githubusercontent.com/2778393/32485028-95980f2a-c3aa-11e7-86e1-2b744351836f.jpg)

### Expected result  
Step 2 -> The value is visible when hovered
Step 4 -> All years in the dropdown are visible

**Note**: This is not reproduced with "bootstrap 3.0.0"

**Comment by desig9stein** [comment]
Hi @dafo, you are using Infragistics theme which is not meant to be used with bootstrap, our bootstrap themes are under bootstrap3 and bootstrap4 folders. Whats the point to have bootstrap themes if all of our themes have to support bootstrap.

**Comment by dafo** [comment]
I am closing this issue. 
I am attaching a new sample that lists all the available Ignite UI Bootstrap themes. 
[sample-bootstrap.zip](https://github.com/IgniteUI/ignite-ui/files/1508927/sample-bootstrap.zip)
Here is the Ignite UI bootstrap theme generator that can be used to create a custom bootstrap theme - https://www.igniteui.com/bootstrap-theme-generator
