### ISSUE TITLE
Character is not entered at first key press in Edge v.41

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#1385]
### Description  
When you have a mask editor (date editor, date picker) opened in Microsoft Edge version 41, if you try entering a character using the keyboard - the character is not entered the first time you press the key. The first press is selecting the placeholder (like if you have pressed <kbd>Shift</kbd> + &rarr;) and the second key press is actually entering the character in the input. 
This is because of a change in the browser as this issue was not reproduced in Microsoft Edge version 40. 

### Steps to reproduce  

1. Create a mask editor (date editor or date picker)
`$('#editor').igMaskEditor({});`
2. Click inside the input to focus the editor
3. Press <kbd>1</kbd>

### Result  
The editor is empty - only the first position is selected

### Expected result  
The editor is showing "1_________"

**Comment by Lipata** [comment]
Here is the Edge [bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15066946/).

**Comment by Lipata** [comment]
Confirmed by Microsoft team.
