### ISSUE TITLE
Grid width is incorrect when there are fixed columns and virtualization

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/ignite-ui#1405]
### Description  
When the grid has fixed columns the width of the grid messed up.

The issue starts reproducing with the following commit https://github.com/IgniteUI/ignite-ui/commit/e2ce983a5678c3a4f12046eaa7d5006ce6680a71

It is automated and the following test is failing due to it - "Test resizing initially fixed when there are Paging, Selection and RowSelectors" (in columnfixing/resizing tests)
It is also related to bug #209490

### Steps to reproduce  

1. Open the attached sample

### Result  
Virtual container of the grid is 606px.

### Expected result  
Virtual container of the grid should be 600px.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/1182001/33553473-9b5ac21a-d901-11e7-855f-4757781a702d.png)
[sam - ColumnFixing.zip](https://github.com/IgniteUI/ignite-ui/files/1527053/sam.-.ColumnFixing.zip)

**Comment by desig9stein** [comment]
@dkamburov the issue is caused by the !important rules which I already removed. Should be fine after TFS-246065 is closed.

**Comment by desig9stein** [comment]
@dkamburov, No, there are 3 PR for 17.1, 17.2, and 18.1 that have to be merged:
[https://github.com/IgniteUI/ignite-ui/pull/1390](url)
[https://github.com/IgniteUI/ignite-ui/pull/1389](url)
[https://github.com/IgniteUI/ignite-ui/pull/1388](url)

**Comment by dkamburov** [comment]
I see, thank you, I will link those pull requests to the bug and let's leave this issue open until the test is resolved.

**Comment by kdinev** [comment]
@dkamburov Did you guys test the behavior? Is everything resolved?

**Comment by dkamburov** [comment]
The issue to be resolved, so I'm closing the issue.
