### ISSUE TITLE
Input value is discarded upon lost focus while in composition mode on IE11 and Firefox

### ISSUE THREAD

**Issue by ymita** [IgniteUI/ignite-ui#1417]
### Description  
Input value is discarded upon lost focus while in composition mode on IE11 and Firefox

### Steps to reproduce  
1. Set focus on igDatePicker
2. Enable Japanese IME mode
3. Enter “２０１３０４０４” in composition mode
4. Focus out from igDatePicker

### Result  
Input value is discarded on lost focus.

### Expected result  
Input value is processed on lost focus.

### Attachments  
[index.zip](https://github.com/IgniteUI/ignite-ui/files/1533708/index.zip)

**Comment by kdinev** [comment]
@ymita What versions does this apply to?

**Comment by ymita** [comment]
@kdinev 17.1, 17.2 and 18.1.
