### ISSUE TITLE
The  cursor is not moving to the right when text reached to the control’s width when "toUpper" is set

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#1419]
### Description  
When `toUpper :true`, the cursor is not moving further to the right when reaching the right border of the input. However, entering more symbols is allowed but the cursor should continue moving like when "toUpper" is set to false.

### Steps to reproduce  

1)Run the sample.
[igTextEditor.zip](https://github.com/IgniteUI/ignite-ui/files/1538583/igTextEditor.zip)
2)Start typing the text in the textEditor.

### Result  
Cursor stopped moving to the right when it reached to the control width though it is letting you type up to the maxLength.

### Expected result  
Cursor should move right the way it is working when I set toUpper to false.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
I have logged public bugs for [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=806233) and [Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15637833/) and will wait for responses.

**Comment by Lipata** [comment]
Both confirmed those issues, so I'm closing the bug as third-party.
