### ISSUE TITLE
Scroll bar on Samples page do not go all the way down (happens from time to time)

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/ignite-ui#1420]
### Description  
Scroll bar on Samples page do not go all the way down (happens from time to time). Also there are random arrows that show also from time to time when you hover over the ends of the scroll bar.

### Steps to reproduce  

Load the samples page and try to scroll down.

https://www.igniteui.com/scroll/styling-dynamic

### Result  
The scroll does not get all the way down.

### Expected result  
The scroll should get all the way down.

### Attachments  
![capture](https://user-images.githubusercontent.com/33216749/33712905-c4446670-db51-11e7-8407-d3feca383345.PNG)

**Comment by skrustev** [comment]
The first issue was issue in the samples.
The second issue is regarding the Samples Browser loading one fonts at first and then another font later on that changes the overall content height, which cannot be detected by the igScroll.

Both of those have PR for the Samples Browser that would fix them. They are not issues in the igScroll.

**Comment by SlavUI** [comment]
Closing the issue :)
