### ISSUE TITLE
igScroll doesn't scroll properly in Edge if you scroll slowly with a smooth scrolling trackpad.

### ISSUE THREAD

**Issue by gmurray81** [IgniteUI/ignite-ui#1438]
### Description  
There is no movement with igScroll if you scroll slowly with a trackpad wheel action, for a smooth scrolling trackpad e.g. the Macbook Pro trackpad.

### Steps to reproduce  

1. Open an igScroll sample in Edge on a machine with a smooth scrolling trackpad.
2. Perform the wheel action slowly (e.g. a 2 finger pan).

### Result  
No scrolling occurs. If you look at the args in a scrolling event, there is a step, but nothing ever changes scrollTop.

### Expected result  
Scrolling should occur.

**Comment by gmurray81** [comment]
BTW, I believe this is some sort of queue swamping thing maybe. The stuff going on in _scrollY is expensive enough that it may really need to be debounced via RAF. Chrome doesn't have a problem, but Edge/Firefox seem to dislike how crowded things get during the thumb drag on the custom scroll thumb, and during slow scrolling on a trackpad. Meanwhile, if you compare that to when you are in an inertial pan, things perform much better. My guess is that this is because it gets clamped down to 60hz by RAF.

**Comment by gmurray81** [comment]
This is definitely it, btw, I experimented with using RAF within _onWheelContainer and _onMouseMoveVDrag to defer the updates, and this immensely improves the scroll performance in both Edge and Firefox.

**Comment by gmurray81** [comment]
Note, though, that those are likely not the only 2 places that need some help.

**Comment by gmurray81** [comment]
Here's an example of what I mean in terms of adjusting some of those methods:

```js
_isWheelDeferred: false,
        _deferredScrollDelta: 0,

		_onWheelContainer: function (event) {
			if (event.ctrlKey === true) {
				return true;
			}

			var evt = event.originalEvent,
				scrollDeltaY = 0,
				scrollStep = this.options.wheelStep,
				scrolledY, scrolledYDir;

			cancelAnimationFrame(this._touchInertiaAnimID);

			if (!this._bMixedEnvironment) {
				this._bMixedEnvironment = true;

				/* Make sure we are not scrolled using 3d transformation */
				this._switchFromTouchToMixed();
			}

			if (evt.wheelDeltaY) {
				/* Option supported on Chrome, Safari, Opera.
				/* 120 is default for mousewheel on these browsers. Other values are for trackpads */
				scrollDeltaY = -evt.wheelDeltaY / 120;
			} else if (evt.deltaY) {
				/* For other browsers that don't provide wheelDelta, use the deltaY to determine direction and pass default values. */
				scrollDeltaY = evt.deltaY > 0 ? 1 : -1;
            }

            this._deferredScrollDelta += scrollDeltaY;
            if (this._isWheelDeferred) {
                return false;
            }
            this._isWheelDeferred = true;

            var self = this;
            function deferredWheel() {
                self._isWheelDeferred = false;
                var scrollDeltaY = self._deferredScrollDelta;
                self._deferredScrollDelta = 0;

                if (self.options.smoothing) {
                    //Scroll with small inertia
                    self._smoothWheelScrollY(scrollDeltaY);
                } else {
                    //Normal scroll
                    if (self.options.scrollOnlyVBar) {
                        self._startY = self._getScrollbarVPosition();
                    } else {
                        self._startY = self._getContentPositionY();
                    }

                    scrolledY = self._scrollToY(self._startY + scrollDeltaY * scrollStep, true);

                    if (!self._cancelScrolling) {
                        //Trigger scrolled event
                        self._trigger("scrolled", null, {
                            owner: this,
                            smallIncrement: 0,
                            bigIncrement: 0,
                            horizontal: false
                        });
                    }

                    /* Check if the browser scroll in the oposite direction. Happens in IE when the content's heigh is for ex. 140.3 and not a round number */
                    /* When the content scrolls to the bottom on IE it might start to scroll very small ammoung up and down while scrolling only down with the mouse wheel*/
                    scrolledYDir = scrolledY > 0 ? 1 : -1;
                    return !scrolledY || (Math.abs(scrollDeltaY) === 1 && scrolledYDir !== scrollDeltaY);
                }

            }
            requestAnimationFrame(deferredWheel);

			return false;
		},
```

**Comment by skrustev** [comment]
Hi @gmurray81, I am looking into what you are describing on Macbook Pro and when using 2 finger pan to scroll up and down the igScroll is scrolling. I tested it on Firefox and it is working there as well, despite scrolling a bit too much compared the other browsers. 

What sample are you running to test this? Do you experience the same on this basic sample I've attached:  [defaultTable-igScroll.zip](https://github.com/IgniteUI/ignite-ui/files/1659272/defaultTable-igScroll.zip)


Also how are you running Edge on Macbook Pro, since it is not supported officially by Mac OS? Are you using some kind of virtual machine or other methods?

**Comment by gmurray81** [comment]
I was using edge in parallels on the macbook, but iirc, I was also able to repro in Edge on a Lenovo notebook.

I don't think it's reproducible in Chrome, I suspect they throttle the scroll input down to the refresh rate of the monitor, probably.

I was able to repro it on any scrolling sample, IIRC.

Make sure to scroll slowly. If you activate the inertia, the intertia is fine, because it throttles the scroll updates through RAF. It's the movement from being swamped by scroll events from the smooth scrolling touchpad that's the issue.

I noticed the FF behavior also. That's likely a separate bug. Might not be normalizing the FF wheel Delta appropriately?

**Comment by skrustev** [comment]
I think I might have reproduced what you described on Edge, but from what I can see it is not the problem because the scroll event is fired too much. I noticed that the delta Edge provide is really low compared to other browsers but I am not sure if this is causing this so much.

Can you check on your end if only scrolling down is not working while scrolling up is fine despite the small increments?

**Comment by gmurray81** [comment]
You are right, the upward scrolling does seem better. I assume the increments are very small because its trying to do "pixel scrolling" rather than scrolling by wheel increments, so the values are probably relative to the actual distance you've moved the fingers since the last update. 

I know throttling the events definitely fixed it, but maybe there's another solution.

When I was profiling it, it seemed that the event was firing so often that some of the DOM reads to determine the current scroll position were expensive enough that that along was causing a problem, so things were just getting swamped. But that doesn't fit with the upward scroll seeming to work properly... 

I thought I remembered both directions working poorly, but I was using igScroll with some other logic, rather than igGrid, so I either I'm remembering incorrectly, or there was some other factor.

**Comment by gmurray81** [comment]
BTW, IIRC Firefox was performing pretty poorly until I added the throttling too.

**Comment by gmurray81** [comment]
But again, different logic that igScroll was interacting with.

**Comment by gmurray81** [comment]
BTW, in practical terms, we probably don't need to respond to scroll more often than RAF can get new animation frames, since presumably the compositor wont be rendering extra scroll frames between those times ;-)

**Comment by gmurray81** [comment]
Not 100% gauranteed to be true.... Compositor may cheat. I haven't noticed any loss of position sync as a result of throwing to RAF frequency, though.

**Comment by skrustev** [comment]
Using RAF change in the wheel event for me has no change on my end, but this probably varies on what machine Edge and Firefox are running.
On slower machines using Firefox it could be an improvement because the scrolling then is called less times per second and the browser isn't spammed with requestAnimationFrames too much when using smooth scrolling of the igScroll. 

There are issues that arise from the method with deferred RAF like not knowing what to return. This results in the limitation to not be able to scroll the page if you are at the end of the content, which was applicable only for smooth scrolling and now it is also applicable with the normal one.
 
Anyway I can probably defer only the smooth scrolling so it doesn't occur so much or when spammed with wheel events it doesn't trigger other smooth scrolling inertias that lower the performance.
This still leaves the issue with scrolling down slowly on Edge though and I will see if I can find the cause.

**Comment by gmurray81** [comment]
Hmm... I know what you mean about letting the page pan. You could probably have the special case where if you know you are at the end of the content you could immediately return that you aren't handling the event, and let it bubble.

RAF on the smooth scroll definitely helped for me...

Is if behaving like this for you? If you try to slowly pan down, the view doesn't seem to move at all, but when you fling, it does?

I agree that RAF adds some complications, but still may be a good move since it should mean nothing needs to recalculate based on the position more often than the monitor refresh rate. 

Question is, why would edge be sending more than 60hz scroll changes anyhow? Maybe Edge has a bug? 

BTW I noticed similar behavior in a different custom scroller elsewhere on the web when searching for whether the problem was isolated. So I don't think it's unique to igScroll.

**Comment by gmurray81** [comment]
For an actual mouse wheel, RAF probably has no effect either way, since the wheel doesn't click that often, and probably doesn't need any throttling.

**Comment by skrustev** [comment]
Yes it is behaving like that on my end as well, it is event more prominent when not using smooth scrolling.
The deferred wheel doesn't change that for me though. If you log the scroll event you will see that there are occasions that the scroll event is fired but no scrolling is done. This is for both non deferred and deferred variant.
The deferred wheel is helping with the performance of the smooth scrolling though as I said earlier when there is too much scrolling done.

I don't think the scroll event has any correlation to the refresh rate of the monitors. It has more likely correlation to the trackpad and how each browser handles firing the scroll event. 

Yes for mouse wheel it doesn't have much of an effect, but still when you fling the wheel you create a lot of scroll events and if the user's machine can't handle it will result and choppyness as well.

**Comment by gmurray81** [comment]
Ok, so you are seeing the deferral help with the smooth scroll, but not the wheel?

The wheel could be a separate issue. If you spam the queue too much, it may be too expensive for other reasons. If it is moving the view in the grid fast enough, it may mean that it is bringing enough new rows into view each wheel event that this is creating enough overhead to slow things down. But that could be a separate issue unrelated to the smooth scroll problem. Do you see the same behavior if you use igScroll with some basic content, rather than the grid?

I was able to repro the smooth scroll issue with some vanilla content, IIRC. I'll try again. So I think that was unrelated to how expensive the code hooked to igScroll's scrolling/scrolled event was, but maybe the wheel issue you are seeing is more related to overhead from that event if many rows are coming in and out of view? Virtualization helps less if most of the rows are being invalidated every wheel tick.

Well, I mentioned that I would expect the browsers to throttle the frequency of the smooth down to the refresh rate of the monitor because there really isn't a compelling reason for them to fire the event more frequently than that. If they aren't prepared to display a new frame of the scroll, why give you intermediate positional events? There could be some rationale I'm not thinking of. Anyhow, I assume that this is why we don't see the issue from chrome. Likely they are throttling the smooth scroll events more aggressively.

**Comment by gmurray81** [comment]
yeah, I can repro the smooth scroll issue with this content:
https://www.igniteui.com/scroll/overview

Still, its very odd that down is more of an issue that up...... something very strange going on there.

**Comment by skrustev** [comment]
This should fix the no movement when scrolling down. If you experience any performance issues that you said earlier you should log another issue so we can look at it.

**Comment by SlavUI** [comment]
Clsoing the issue
