### ISSUE TITLE
[igDialog] The igdialogstatechanged event is not fired when opening the dialog programmatically

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/ignite-ui#1513]
### Description  
The **igdialogstatechanged** event is **not** fired when opening the dialog programmatically.
(For example when setting the state to "opened" on a button click.)

**NOTE:**
The issue is not reproduced when maximizing the dialog instead of opening it.

### Steps to reproduce  

1. Download the sample html file and open it.
2. Close the igDialog either with its own close button or with the "close dialog" button on the left.(igdialogstatechanged will fire as expected).
3. Open the igDialog by clicking the "open dialog" button on the left.

### Result  
The igDialog is opened, but the igdialogstatechanged event is **not** fired.

### Expected result  
The igDialog is opened and the igdialogstatechanged event is fired.

### Attachments  
[igDialogSample.zip](https://github.com/IgniteUI/ignite-ui/files/1614868/igDialogSample.zip)

**Comment by dafo** [comment]
statechang**ING** event is also not fired in this scenario.

**Comment by dafo** [comment]
The events should not be triggered when changing the state programatically.
