### ISSUE TITLE
[igTree] Check mark on the parent node is not black after all the children are checked

### ISSUE THREAD

**Issue by ymita** [IgniteUI/ignite-ui#1516]
### Description  
Check mark on the parent node is not black after all the children are checked.

### Steps to reproduce  
1. Run the attached sample
2. Check "Computer" node to select all children
3. Uncheck "My Documents"
4. Check "My Documents" again

### Result  
Checkbox on "Computer" node is gray.

### Expected result  
Checkbox on "Computer" node is black, as same as the appearance after step 2.

### Attachments  
[index.zip](https://github.com/IgniteUI/ignite-ui/files/1617364/index.zip)

**Comment by kdinev** [comment]
@ymita What versions do you reproduce this in?
