### ISSUE TITLE
Upload does not start automatically(autostartupload: true) when useSingleRequest is true.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/ignite-ui#1532]
### Description  
Files are not uploaded automatically when useSingleRequest and autostartupload are both true.

### Steps to reproduce  

1. Load the attached sample
2. Select a couple files to upload

### Result  
The files are displayed but the upload button should be pressed to start the upload.

### Expected result  

The upload should start. 

### Attachments  
[igUpload.zip](https://github.com/IgniteUI/ignite-ui/files/1626624/igUpload.zip)

**Comment by DDavidkov** [comment]
This should be resolved by later commits for the feature.
