### ISSUE TITLE
The igdialogstatechanged/ing event is fired when changing the state programmatically

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#1535]
### Description  
Events are triggered when changing the state of the dialog programatically.

### Steps to reproduce  

1. Runt he attached sample
2. Click any of the following buttons:

- maximize dialog
- minimize dialog
- close dialog

### Result  
igdialogstatechanged event is fired

### Expected result  
The event is not fired as the state is changed programatically. It should be only triggered when changed via the UI.

### Attachments  
[igDialogSample.zip](https://github.com/IgniteUI/ignite-ui/files/1631977/igDialogSample.zip)

**Comment by PlamenaMiteva** [comment]
By design this is the expected behavior of the igDialog as described in the control's documentation.
