### ISSUE TITLE
Feature chooser icons are not styled correctly when igGrid is used in igSplitter

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/ignite-ui#1580]
### Description  
Feature chooser icons are not correctly styled (height and width) when igGrid is located in igSplitter control.

### Steps to reproduce  

1. Run the attached sample.
2. Open feature chooser.
3. Observe feature chooser icons.

### Result  
Icons in the feature chooser do not have the correct styling applied.
![igsplittergrid](https://user-images.githubusercontent.com/13034836/35808076-60d9388e-0a8d-11e8-80da-bcd7fcd1b67a.png)
P.S I noticed that the following class is causing the issue:
.ui-igcombo .ui-icon, .ui-igedit .ui-icon, .ui-iggrid tr .ui-icon, .ui-igsplitter .ui-icon, .ui-igtree .ui-icon {
    height: 16px!important;
    width: 16px!important;
    font-size: 11px;
}
height and width from this class are overwriting the feature chooser icons default height and width, I believe the selector for the splitter icon, where this class should be applied,  could be changed to something like ui-splitter-icon
### Expected result  
Feature chooser icons to have the correct width and height.
![iggrid](https://user-images.githubusercontent.com/13034836/35808409-570a7fd8-0a8e-11e8-816c-da0a2cefba65.png)

### Attachments  
[igGridWithinIgSplitter.zip](https://github.com/IgniteUI/ignite-ui/files/1695384/igGridWithinIgSplitter.zip)

**Comment by mpavlinov** [comment]
@desig9stein Can you fix it in 17.2 and 17.1 please.

**Comment by desig9stein** [comment]
@mpavlinov  the problem is not appearing there.
