### ISSUE TITLE
keydown event doesn't bubble up to document when maxLength option is set to igTextEditor.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/ignite-ui#1590]
### Description  
keydown event doesn't bubble up to document when maxLength option is set to igTextEditor.

Here is a scenario.
```
document.onkeydown = function (e) {
    // Want to handle all the keydown events including igTextEditor, normal input and so on.
    console.log(e);
}
```

### Steps to reproduce  

1. Open the attached sample html.
2. Open the browser console.
3. Type 4 characters in the igTextEditor.

### Result  
3. When typing 4th character, keydown event for document doesn't fire.

### Expected result  
3. When typing 4th character, keydown event for document should fire.
By the way, keydown event bubbles up on other editors.

### Attachments  
[igEditors.zip](https://github.com/IgniteUI/ignite-ui/files/1709912/igEditors.zip)

**Comment by kdinev** [comment]
@tkiryu Other editors don't have an applicable `maxLength` option. 

Why does invalid input have to be propagated to the document? The current behavior is that all invalid input for the `igTextEditor` is ignored and is not propagated.

**Comment by alhalama** [comment]
@kdinev What if you wanted to have keyboard shortcuts on the website where you were listening for a specific combination of special keys with a character and the event didn't fire?

**Comment by kdinev** [comment]
Then you would bind to the editor's keydown event, which is still triggered: 

https://github.com/IgniteUI/ignite-ui/blob/master/src/js/modules/infragistics.ui.editors.js#L2902

**Comment by alhalama** [comment]
There are many websites/applications that use keyboard shortcuts including: [GitHub](https://help.github.com/articles/using-keyboard-shortcuts/), [Yammer](https://support.office.com/en-us/article/keyboard-shortcuts-for-yammer-eb92ca45-97f0-4b9e-a0a8-b0105b3b098f), [Twitter](https://venturebeat.com/2014/11/30/how-to-use-twitter-with-keyboard-shortcuts/), [Outlook](https://support.office.com/en-us/article/keyboard-shortcuts-in-outlook-on-the-web-63df572e-1078-4562-b45e-b93e07a76ffb).  Depending on the purpose of the shortcut, you might want it to still work if an editor has focus if it uses a modifier key and not need to listen to multiple handlers.

**Comment by kdinev** [comment]
This is still by design. By default the space button, for example, scrolls the page, but inputs do not propagate it so you don't get the scroll.

**Comment by alhalama** [comment]
If you use a html input of type text and set the maxlength, you can still handle the keydown of the document when the maxlength has already been reached.  Shouldn't we be consistent with this?
