### ISSUE TITLE
compactData option of igCombo is missing from the API docs

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/ignite-ui#1598]
### Description  
igCombo does not have its compactData property described in the help API.

### Steps to reproduce  

1. Go to https://www.igniteui.com/help/api/2017.2/ui.igcombo
2. Click on Options

### Result  
CompactData property is not present.

### Expected result  
CompactData property should have description and code snippet

**Comment by kdinev** [comment]
@tiliev This is an internal option used for the MVC wrapper.
