### ISSUE TITLE
igTree findNodesByText doesn't escape apostrophe symbol, if available in search text

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/ignite-ui#1604]
### Description  
If tree is having nodes, which text contains apostrophe, then using the method findNodesByText to find such a node, will not work

### Steps to reproduce  

1. Open this [sample](http://jsfiddle.net/PlamiM/zk42xx5d/)
2. Go to findNodesByText method

### Result  
findNodesByText method deosn't find the node with text _Europe's_

### Expected result  
findNodesByText method returns node with text _Europe's_

**Comment by PlamenaMiteva** [comment]
This is not a bug. I changed the sample as the findNodesByText() was called on the wrong selector and now the method works just as expected.
