### ISSUE TITLE
Data Source settings are not cleared between new instances of the ig.DataSource.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/ignite-ui#1639]
### Description  
Data Source settings are not cleared between new instances of the ig.DataSource.

### Steps to reproduce  

1. Run the attached sample.
2. Note that ds1 has some filtering settings applied.
3. Note that when a new instance of ig.DataSource is created (ds2) it has the same value for its filtering setttings.
### Result  
Settings applies to one instance are applied to new instances.

### Expected result  
New instances should not be poluted by values set on previous instances. They should always be cleared.

### Attachments 
[dsIssue.zip](https://github.com/IgniteUI/ignite-ui/files/1775984/dsIssue.zip)

**Comment by mpavlinov** [comment]
@MayaKirova As we discussed this issue its too risky to change the Class implementation. I'm closing the issue.
