### ISSUE TITLE
igScroll flickering test

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/ignite-ui#166]
The first CI run for #165 (single unrelated test change) failed with the following:

> Testing tests/unit/scroll/tests.html .........................................F...............................................
> igScroll - clicking on arrow up once scrolls the content test.
> Message: igScroll did not update scrollbar position properly
> Actual: "11.2164"
> Expected: "5.6082"
> at file:///home/travis/build/IgniteUI/ignite-ui/bower_components/qunit/qunit/qunit.js:1485
>   at file:///home/travis/build/IgniteUI/ignite-ui/bower_components/qunit/qunit/qunit.js:2194
>   at file:///home/travis/build/IgniteUI/ignite-ui/tests/unit/scroll/tests.html:1283

**Comment by damyanpetev** [comment]
And one more assert from #171 :
> igScroll - clicking on the horizontal track left of the thumb drag scrolls the content test.
> Message: igScroll did not scroll properly
> Actual: 138.75
> Expected: 0
> at file:///home/travis/build/IgniteUI/ignite-ui/bower_components/qunit/qunit/qunit.js:1485
>   at file:///home/travis/build/IgniteUI/ignite-ui/bower_components/qunit/qunit/qunit.js:2194
>   at file:///home/travis/build/IgniteUI/ignite-ui/tests/unit/scroll/tests.html:1905

**Comment by skrustev** [comment]
Not failing for extensive period after merging so assuming they are fixed.
