### ISSUE TITLE
textChanged event is not triggered when allowNullValue option is set to true,  editor loses focus and afterwards text is cleared with "x" button

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/ignite-ui#1666]
### Description  
textChanged event is not triggered when the allowNullValue option is set to true,  editor loses focus and afterwards text is cleared with "x" button.

### Steps to reproduce  

1) Run the attached sample.
2) Enter some value in the text editor.
3) Click outside of the editor in order to lose focus.
4) Click "x"(clear) button of the editor.
5) Observe the events fired.

Please note that this was working as expected in version 16.2
I am logging this with High severity because the issue appears in Filtering feature, where we the textChanged event is handled and it is visible in the samples browser.
### Result  
Only the valueChanged event is fired.

### Expected result  
Both textChanged and valueChanged events to be fired

### Attachments  
[251229.zip](https://github.com/IgniteUI/ignite-ui/files/1819856/251229.zip)

**Comment by damyanpetev** [comment]
Closing as it's already merged into 18.1 (skipping the wait for master merge).
