### ISSUE TITLE
igVieoPlayer does not resume video at selected position after commercial

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/ignite-ui#1670]
### Description  
If you have a video with some commercials and fast forward the player to a given position after a commercial, the playback does not resume at selected position.

### Steps to reproduce  

1. Add a commercial, let say at 10th second of a video;
2. Run the video;
3. Fast forward to a position after the commercial, let say click on 20th second;

### Result  
After commercial finishes the video continues from the position exactly after the commercial, in this case from 10th second.

### Expected result  
Commercial should play and after it finishes the video should continue at the selected position, in this case from 20th second.

**Comment by Lipata** [comment]
For the moment this is the current behavior. You can notice that while the commercial is playing the progress is at the commercial start time. This will require some development and it is more like a feature.
