### ISSUE TITLE
The second panel of the igSplitter disappears when moving the splitter and then resizing the browser

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/ignite-ui#1696]
### Description  
The second panel of the igSplitter disappears when moving the splitter and then resizing the browser.
The issue is reproduced on Chrome, Firefox, IE and Edge when performing random movements of the splitter and then resizing actions over the browser.

NOTES:
The issue is not reproduced with horizontal orientation.
The attached zip contains a gif which demonstrates the issue.

### Steps to reproduce  

1. Download and run the attached sample in maximized browser window.
2. Move the splitter to the left.
3. Start resizing the browser window randomly

### Result  
The right panel eventually disappears.

### Expected result  
The right panel does not disappear.

### Attachments  
[SampleAndGif.zip](https://github.com/IgniteUI/ignite-ui/files/1898529/SampleAndGif.zip)

**Comment by rmkrmk** [comment]
Adding a sample with is using igTree (not igGrid) and the issue is still reproducible
[SplitterWithTreeSample.zip](https://github.com/IgniteUI/ignite-ui/files/2690512/SplitterWithTreeSample.zip)
