### ISSUE TITLE
Adjust tests to jQuery 3.0

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui#17]
- [x] igCombo
- [x] igDataSource
- [x] igDialog 
- [ ] igToolbar
- [x] igUpload

**Comment by kdinev** [comment]
@Lipata Please update the tests to run against jQuery 3.0 again!

**Comment by kdinev** [comment]
@Lipata what other tests are currently not compatible with jQuery 3.0. I will include them to the checklist in the issue.

**Comment by Lipata** [comment]
@kdinev igDialog, igToolbar, igUpload. Here is the [latest build](https://travis-ci.org/Lipata/ignite-ui).

**Comment by Lipata** [comment]
@kdinev igDataSource tests are already fixed.

**Comment by Lipata** [comment]
@zdrawku & @hanastasov. When you run html editor tests with jQuery 3.0, toolbar tests are failing, with the [following error](http://stackoverflow.com/questions/16077280/uncaught-error-syntax-error-unrecognized-expression-unsupported-pseudo). As the article suggests, it is good, when using pseudo-classes, to escape any special characters, in this case the colon. I've did that inside the toolbar.js file, but unfortunately the basic rendering tests are hanging. Can you check if this is a solution, and if it needs additional fixes. Thanks.

**Comment by kdinev** [comment]
Postponing this issue, due to incompatibilities between jQuery 3.0 and jQuery UI.

**Comment by Lipata** [comment]
Regarding the failing igDIalog tests, they are failing, because of the [following change](https://github.com/jquery/jquery/issues/3181#issuecomment-226964470) in jQuery 3.0.0. This change needs some adaptions in jQuery UI, which are to be implemented yet.
