### ISSUE TITLE
Unable to select a row/node with igTreeGrid

### ISSUE THREAD

**Issue by walteralvarado** [IgniteUI/ignite-ui#1718]
I understand that igTreeGrid inherits from igGrid and the method selectRow seems to be available, however I can't get it to work.

`<table id="myIGTreeGrid"></table>`

```
$("#myIGTreeGrid").igTreeGrid({
	width: "100%",
	dataSource: productsDataSource,
	initialExpandDepth: 0,
	autoGenerateColumns: false,
	height: "100%",
	primaryKey: "id",
	showFooter: false,
	columns: productColumns,
	childDataKey: "products",
	features: [ { name: "Selection" }, ]
});
```

When I call `$("#myIGTreeGrid").igGridSelection("selectRow", 0);` I get this error

cannot call methods on igGridSelection prior to initialization; attempted to call method 'selectRow'

**Comment by MayaKirova** [comment]
Selection API methods for the TreeGrid should be invoked via the TreeGridSelection feature.
It’s a separate widget so the API methods should be called on igTreeGridSelection, for example:
$("#myIGTreeGrid").igTreeGridSelection("selectRow", 0)
For more details please refer to the API:
https://www.igniteui.com/help/api/2018.1/ui.igtreegridselection#methods:selectRow

**Comment by mpavlinov** [comment]
Closing this one as it is a couple of months old now.
