### ISSUE TITLE
Validation options range values do not update when bound to knockout

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/ignite-ui#1726]
### Description  
The editor decrements and increments to the original min/max ranges set

### Steps to reproduce  

1) Run Sample
2) Increment the "From" editor until the error message appears
3) Decrement the "To" editor until the error message appears
4) Follow steps 2 and 3 in reverse order

### Result  
The error message shows the original min/max values

### Expected result  
The error message should show the values of "From" and "To"

### Attachments  
[NumberRange.zip](https://github.com/IgniteUI/ignite-ui/files/2005188/NumberRange.zip)

**Comment by Lipata** [comment]
When the "From" value is decreased, then you need to update "To" validation settings as well its minValue:

```
opt = $("#toAge").igNumericEditor("option", "validatorOptions");
$("#toAge").igNumericEditor("option", "minValue", from);
$("#toAge").igNumericEditor("option", "validatorOptions", { valueRange: { min: to, max: opt.max }});
```

Then editors and their validation message are shown correctly.
