### ISSUE TITLE
Icon can't be loaded when I use CDN

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/ignite-ui#1727]
### Description  
Icon can't be loaded when using CDN. Please see the image below.
![icondownloaderror](https://user-images.githubusercontent.com/7350918/40213516-d543ad00-5a90-11e8-8a18-33c72b56a756.png)

This happens with 17.2 and 18.1.

**Comment by mpavlinov** [comment]
@gdayori Please check again. This should already be fixed.
