### ISSUE TITLE
Selected year and items in year drop-down are not visible.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/ignite-ui#1734]
### Description  
Items in year drop-down are not visible when bootstrap.css is included.

### Steps to reproduce  

1. Open the [following demo](https://jsfiddle.net/7kzv101r/1/)
2. Expand the calendar
3. Note the year
4. Open year drop-down.

### Result  
The selected year is not visible. The normal items have their color set to white(they inherit from the parent) and are not visible.

### Expected result  
All items should have an appropriate fore-color.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/16817847/40845498-8920504c-65bf-11e8-9b2f-48e48578efb9.png)

**Comment by dafo** [comment]
I think this is the very same issue I have previously created: https://github.com/IgniteUI/ignite-ui/issues/1371

This issue can be closed I think.
