### ISSUE TITLE
Financial Chart Styling Updates

### ISSUE THREAD

**Issue by andiesm** [IgniteUI/ignite-ui#1774]
@desig9stein 

Things to style:

- Indicators dropdown
- Legend Item Styling
- Chart type dropdown
- Toolbar styling (padding / spacing fixes)

Things that will be styled in the future (currently not implemented)
- Searchbox inside Indicators Dropdown
- Settings menu
- Date pickers

Reference 
![charttypedropdown](https://user-images.githubusercontent.com/37708383/43789801-49c2f4b0-9a47-11e8-9bee-ff0d5328f369.png)
![datepickers_notimplemented](https://user-images.githubusercontent.com/37708383/43789803-49ea80c0-9a47-11e8-950c-c3369d230950.png)
![indicatorsdropdown](https://user-images.githubusercontent.com/37708383/43789804-4a0f7416-9a47-11e8-89c9-c95055e7b80d.png)
![legenditem](https://user-images.githubusercontent.com/37708383/43789806-4a31d858-9a47-11e8-9057-06f9a2b8e07f.png)
![search_notimplemented](https://user-images.githubusercontent.com/37708383/43789807-4a55fe40-9a47-11e8-9c0b-82d121365578.png)
![settings_notimplemented](https://user-images.githubusercontent.com/37708383/43789808-4a80f15e-9a47-11e8-9efa-76afb150d27f.png)
![toolbar](https://user-images.githubusercontent.com/37708383/43789809-4ae5cd4a-9a47-11e8-8205-c75776c4ac4f.png)

Images attached for all features (implemented and not implemented).

**Comment by StefanIvanov** [comment]
Thanks for creating the issue Andie, Marin is working on it
