### ISSUE TITLE
Auto-fill does not update igTextEditor

### ISSUE THREAD

**Issue by alexalex972** [IgniteUI/ignite-ui#1776]
### Description  
The textChanged event should trigger when form's autocomplete is on.

### Steps to reproduce  
1. Open the attached sample.
2. Open IE11 or Firefox and enable its auto-fill functionality to store user name and password in forms.
3. Type something as username and password. (An alert box pops up while typing as the textChanged event is triggered)
4. Click "Login".
4. You'll see a prompt window which asks you whether or not you would like to store the user name and the password. Answer "Yes" to it.
5. Click twice on "User Name" text box. You'll see a drop down open.
6. Select the username from the drop down.

### Result  
The textChanged event is not triggered.

### Expected result  
The textChanged event should be triggered.

### Attachments 
[autofill-sample.zip](https://github.com/IgniteUI/ignite-ui/files/2286835/autofill-sample.zip)

**Comment by damyanpetev** [comment]
Updated title - auto-fill should not only trigger `textChanged` but also `valueChanged` and most importantly update the actual value of the editor.
