### ISSUE TITLE
Cannot upload a file inside archive via drag and drop

### ISSUE THREAD

**Issue by astaev** [IgniteUI/ignite-ui#1835]
### Description  
Cannot upload a file inside archive via drag and drop

### Steps to reproduce  

1. Open the attached project
2. Navigate to [projDir]\Resources folder 
3. Open the .zip file inside file explorer
4. Drag and drop the .txt file into the "UploadFile" area

### Result  
An error occurs and filePath is empty

### Expected result  
File should be uploaded without errors

### Attachments  
[igUploadSample.zip](https://github.com/IgniteUI/ignite-ui/files/2556905/igUploadSample.zip)

**Comment by dkamburov** [comment]
I investigated this and there is nothing we can do about it. When uploading a file from a zip, the server does not receive any file information(file name, file size, file content). Looks like there is a restriction from the file explorer or could be the browser not knowing where the temporary extracted file is.

Closing this as a third party issue, please re-open if there are further questions.
Also note that this scenario is working on Edge, which also confirms that this is third party issue.
