### ISSUE TITLE
Scrollbar arrows are disappearing in Firefox after click, hold and move the mouse away

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/ignite-ui#184]
Steps to reproduce:

1. Run igScroll under Firefox
2. Click and hold on any of the scrollbar arrows
3. Move the mouse away

The arrow disappears:

![screenshot](https://cloud.githubusercontent.com/assets/1182001/17400624/97d5d9ac-5a51-11e6-9b90-636ca36b3eb2.png)

**Comment by mpavlinov** [comment]
#200

**Comment by mpavlinov** [comment]
fixed by #200
