### ISSUE TITLE
Typescript Typings Out of Date on Nuget and NPM

### ISSUE THREAD

**Issue by MDendura** [IgniteUI/ignite-ui#1892]
The latest version of the [IgniteUI](https://www.nuget.org/packages/IgniteUI) package on Nuget is 18.2.83.
* The [IgniteUI.TypeScript.Definitions](https://www.nuget.org/packages/IgniteUI.TypeScript.Definitions) package is at 16.2.20162.2040.
* The [@type/ignite-ui](https://www.npmjs.com/package/@types/ignite-ui) package on npm is at 18.1.2.

Please update the typings files on both NuGet and NPMJS to match the current release.

**Comment by mpavlinov** [comment]
@MDendura Thanks for the feedback. We will update them next week.

**Comment by MDendura** [comment]
Any news on this update?

**Comment by dkamburov** [comment]
Changing this to in-progress, as we've already started working on it. Hopefully we'll have them updated soon.

**Comment by mpavlinov** [comment]
Linking the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32820

**Comment by mpavlinov** [comment]
@MDendura We've updated the NuGet Package: https://www.nuget.org/packages/IgniteUI.TypeScript.Definitions. Still waiting for the maintainers of the DefinitelyTyped repo to merge our PR.

**Comment by MDendura** [comment]
@mpavlinov Thanks - I'll give them a test. 

Hopefully it will mean I can reduce the casts to `any` in my TypeScript project.

**Comment by dkamburov** [comment]
The pull request to DefinitelyTyped is merged, the 18.2.0 typings are also available at npm [@types/ignite-ui](https://www.npmjs.com/package/@types/ignite-ui)
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32820

**Comment by MDendura** [comment]
They seem to work fine for me - marking as closed.
