### ISSUE TITLE
Static Files not copied to wwwroot for ASP.NET Core project

### ISSUE THREAD

**Issue by MDendura** [IgniteUI/ignite-ui#1899]
### Description  
NuGet package content files not automatically copied to `wwwroot` project directory on build/install in ASP.NET Core project.

### Steps to reproduce  

1. Create a new ASP.NET Core project in VS2017, enabling serving of static files.
2. Add the Infragistics Ignite UI package as a reference.
3. Create a page referencing the Ignite UI JS and CSS.
4. Build and run the project.
5. Note 404 errors in browser console.

### Result  
404 errors as the Ignite UI static files have not been copied into the `wwwroot` folder correctly.

### Expected result  
On install of the NuGet package/build of the project the Ignite UI static files should be available from the `wwwroot` directory.

### Attachments  
See Nuget/Home#4837, where the advice seems to be that a .targets file is needed inside the NuGet package to perform the copying on build.

**Comment by mpavlinov** [comment]
@MDendura Thanks for proposing a fix. We will give it a try.

**Comment by MDendura** [comment]
Hi @mpavlinov - is there any news on this?

**Comment by mpavlinov** [comment]
@MDendura Yes. We have a fix that we're going to release with our next SR.

**Comment by MDendura** [comment]
Thanks on producing a fix for this. Any idea when a release will hit NuGet?

**Comment by mpavlinov** [comment]
@MDendura It will be available with our next SR planned for April 5, 2019. Here is the [schedule](https://www.infragistics.com/support/service-releases).

**Comment by mpavlinov** [comment]
@MDendura checkout the new version [here](https://www.nuget.org/packages/Infragistics.Web.AspNetCore/).

**Comment by MDendura** [comment]
@mpavlinov Thanks, I'll give it a go :+1:

**Comment by MDendura** [comment]
@mpavlinov  Works perfectly. Thanks! :+1:
