### ISSUE TITLE
TimePicker and DateEditor values reset to 12:00 AM when key up/down is pressed.

### ISSUE THREAD

**Issue by sstoyanovIG** [IgniteUI/ignite-ui#1902]
### Description  
TimePicker and DateEditor values reset to 12:00 AM when key up/down is pressed and there is no valid value yet entered in the editor.

### Steps to reproduce  

1. Open http://jsfiddle.net/9fnzy71L/
2. Clear value
3. Type in 08:00
4. Use the right arrow key then press the down arrow to select PM

### Result  
The value is reset to 12:00 AM

### Expected result  
The value should be 08:00 PM

**Comment by TammyD79** [comment]
Is this going to make the April 5th service release?

**Comment by bazal4o** [comment]
@TammyD79  - yes we're going to provide the fix into the April SR
