### ISSUE TITLE
[IE11] Caret appears after igCombo opens when mode option is set to "dropdown"

### ISSUE THREAD

**Issue by ymita** [IgniteUI/ignite-ui#1917]
### Description  
Caret appears after set of steps. Is this an issue with igCombo?

### Steps to reproduce  

1. Run the sample [igCombo.zip](https://github.com/IgniteUI/ignite-ui/files/3041725/igCombo.zip)
2. Select text of `<label>Label to select here</label>` and deselect it by clicking the selected text itself
3. Open igCombo dropdown and select an item
4. Open select tag and select an item
5. Open igCombo dropdown

### Result  
Caret appears on `<label>Label to select here</label>`.

### Expected result  
Caret does not appear.

### Attachments  
[igCombo steps video.zip](https://github.com/IgniteUI/ignite-ui/files/3041780/igCombo.steps.video.zip)

**Comment by kdinev** [comment]
@ymita This is a third-party issue with IE and Edge. It can be reproduced with almost any site, like GitHub, where caret appears in the title of issues, etc. GitHub doesn't have any of our controls.

**Comment by ymita** [comment]
@kdinev I confirmed this is reproduced without igCombo on IE11. When igCombo's mode option is "dropdown", igCombo's `<li>` has unselectable="on". On IE11, caret cannot go to igCombo. So focus moves to the element which is previously focused. In this case, `<label>`. Thanks.
