### ISSUE TITLE
The igTree nodeDropping and nodeDropped events should expose the tree in its arguments

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/ignite-ui#1939]
## Is your feature request related to a problem? Please describe.
The igTree nodeDropping and nodeDropped events should expose the tree (ui.owner) in its arguments, like in the other events (like [nodeExpanded](https://www.igniteui.com/help/api/2019.1/ui.igtree#events:nodeExpanded))

## Describe the solution you'd like
Expose tree in the arguments

**Comment by damyanpetev** [comment]
@PlamenaMiteva @Lipata 
[`dragStart`](https://www.igniteui.com/help/api/2019.1/ui.igtree#events:dragStart) and [`nodeDropping/ed`](https://www.igniteui.com/help/api/2019.1/ui.igtree#events:nodeDropping) already have `ui.data` exposed, which needs to be adjusted for scenarios where the default copy behavior can't handle. It's just the events trigger with a separately generated node. Would be nice if manipulating the data in those events can be reflected back to the Tree drag & drop.

**Comment by damyanpetev** [comment]
Just as FYI, besides the owner, we ended up exposing `sourceNode` to the  [`nodeDropping/ed`](https://www.igniteui.com/help/api/2019.1/ui.igtree#events:nodeDropping). So when dropping a node its child collection can be copied if needed.

To copy a node with its children between igTree-s, the sourceNode data can be extended like so on drop:
https://github.com/IgniteUI/ignite-ui/blob/ea87a00c98b87681a8e3ab43132703b77ca6a74e/tests/unit/tree/tree-test.js#L5273-L5275
