### ISSUE TITLE
String in the inputMask becomes visible after focus leaves

### ISSUE THREAD

**Issue by ymita** [IgniteUI/ignite-ui#1974]
## Description  
Describe the issue.

 * ignite-ui version: 18.2 and 19.1
 * browser: n/a

## Steps to reproduce  

1. Go to https://www.igniteui.com/editors/mask-editor
2. Set focus on and leave from editors

## Result  
String contained in the inputMask becomes visible.

## Expected result  
String contained in the inputMask is invisible if the value is invalid and revert back to empty.

## Attachments
![inputMask behavior](https://user-images.githubusercontent.com/14340675/62349696-73ae2000-b53b-11e9-97eb-73a8e920e02d.gif)

## Note
With the 18.1(18.1.152) version, igMaskEditor behaves as expected.

**Comment by damyanpetev** [comment]
It seems the regression is caused by the fix for https://github.com/IgniteUI/ignite-ui/issues/1853
