### ISSUE TITLE
Update to jQuery 3.4.x breaks some tests

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/ignite-ui#1981]
## Description  
After updating to jQuery 3.4.1 (latest atm) ~10 tests fail pretty consistently.
See this build results for example: https://travis-ci.org/IgniteUI/ignite-ui/builds/572645623#L2384 from PR #1979

There appear to be some changes related to the jQuery 3.4.x  versions of the `focus()` and `blur()` methods:
https://blog.jquery.com/2019/05/01/jquery-3-4-1-triggering-focus-events-in-ie-and-finding-root-elements-in-ios-10/
https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/

We should check if functionality is affected or just the tests failing.
At least for the splitter button we narrowed it down to the lack of `originalEvent` when using the jQuery methods, which is easily worked around with the native methods. 

 * ignite-ui version: 18.2 - 19.2
 * browser: Chrome 76

**Comment by PlamenaMiteva** [comment]
igDatePicker - bug##2002
