### ISSUE TITLE
IE11 : The caret still display in dropdown igcombo

### ISSUE THREAD

**Issue by nguyendhoan** [IgniteUI/ignite-ui#1983]
## Description  
I use igCombo with type=dropdown in IE11.
When i press tab to focus into igCombo, the caret display in igCombo.

 * ignite-ui version: 18.2.72
 * browser: IE11

## Steps to reproduce  
Case 1 :
1. Init igCombo with type=dropdown
2. Set datasource is empty.
3. Press tab to focus into igCombo

Case 2 :
1. Init igCombo with type=dropdown
2. Set datasource is some sample data
3. Press tab to focus into igCombo
4. Press left and right arrow key in keyboard

## Result  
When i press tab to focus into igCombo, the caret display in igCombo.

## Expected result  
The caret don't display in igCombo.

## Attachments  
Code sample

`<script>
$(function () {

var data = [];

$("#combo").igCombo({
dataSource: data, //JSON Array defined above
valueKey: "ID",
mode: "dropdown",
textKey: "Name"
});
});
</script>
<div id="combo"></div>`

**Comment by HristoP96** [comment]
This is dupllicate of #1917, so I will close it, since it is a 3rd party issue.
