### ISSUE TITLE
igDatePicker input does not lose focus when drop down is expanded and suppressKeyboard option is enabled

### ISSUE THREAD

**Issue by PlamenaMiteva** [IgniteUI/ignite-ui#2002]
## Description  
igDatePicker input does not lose focus when calendar is expanded and suppressKeyboard option is enabled. This bug is introduced with the latest jQuery version (3.4.1)
[igDatePickerTest.zip](https://github.com/IgniteUI/ignite-ui/files/3610024/igDatePickerTest.zip)

*  jQuery - v3.4.1
 * ignite-ui version: 19.1
 * browser: All

## Steps to reproduce  

1. Run the attached sample
2. Expand departure date picker

## Result  
The input is focused.

## Expected result  
The input should not be focused.

**Comment by kdinev** [comment]
Moving to `severity: high` as this affects the CI.
