### ISSUE TITLE
igCombo does not remove focus and blur events from the input on destroy

### ISSUE THREAD

**Issue by PlamenaMiteva** [IgniteUI/ignite-ui#2003]
## Description  
[jQuery 3.4.0 release](https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/) introduces some changes regarding [focus, blur and click events](https://github.com/jquery/jquery/commit/669f720edc4f557dfef986db747c09ebfaa16ef5) and as a result focus and blur events are not removed from the input when igCombo is destroyed.

 * jQuery: 3.4.1
 * ignite-ui version: 19.1
 * browser: All

## Steps to reproduce  
Run combo rendering test '[ID4] igCombo input rendering' with jQuery v.3.4.1

## Result  
Focus and blur events are not removed

## Expected result  
Focus and blur events should be removed

**Comment by Lipata** [comment]
There is a bug in jQuery 3.4.0. They attach focus and blur handlers, which are not removed afterward. Temporary one of the asserts is removed.
