### ISSUE TITLE
&lt; cannot be used in node attribute

### ISSUE THREAD

**Issue by ymita** [IgniteUI/ignite-ui#2033]
## Description  
&lt; cannot be used in node attribute. If &lt; is supplied, the node tag is generated in an invalid form.

 * ignite-ui version: 19.2.25
 * browser: any

## Steps to reproduce  

1. Open the attached sample
2. Observe the tree
3. Inspect the top level node which contains &lt;
Line 41
`var xmlDoc = '<OrgChart Name="&lt;All employees">' +`

## Result  
The top level node is not visible. And the generated tag is `<all employees<="" a=""></all>`.
![image](https://user-images.githubusercontent.com/14340675/72579404-57047980-391c-11ea-9d58-e874cc69651a.png)

## Expected result  
The top level node is rendered correctly and is visible. And the generated tag should be something like `<a href="#" target="_self" class="ui-corner-all">&lt;All employees</a>`.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[igtree__xml-binding issue.zip](https://github.com/IgniteUI/ignite-ui/files/4074740/igtree__xml-binding.issue.zip)

**Comment by IvayloG** [comment]
@ymita  This is XML related and not reproducible with JSON binding.
In order for this to work, you can change the format so there is an empty space after the < XML entity replacement - like this **" \&lt; "**

**In short, replace:**
"\&lt;All employees" with 
" \&lt; All employees" OR even
"\&lt; All employees"

**Comment by ymita** [comment]
@IvayloG 
Thank you for your suggestion.
The customer wonders which character cannot be contained in xml data. For example, `&gt;` can be supplied while `&lt;` cannot be. Is this considered a limitation of igTree?

**Comment by IvayloG** [comment]
@ymita 
I will further investigate this issue as it may require an actual behavior fix.
