### ISSUE TITLE
igCombo's dropdown doesn't close in Safari on iOS or in desktop Chrome in responsive mode when some other part in the page is clicked.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/ignite-ui#2055]
## Description  
igCombo's dropdown doesn't close in Safari on iOS or in desktop Chrome in responsive mode when some other part in the page is clicked.

 * ignite-ui version: 19.2
 * browser: Safari on iOS, Chrome in responsive mode on Windows desktop

## Steps to reproduce  
1. open https://www.igniteui.com/combo/editing in Safari on iOS or Google Chrome in responsive mode on Windows.
2. click on the dropdown caret icon beside the dropdown (aka the upsidedown triangle)
3. then click on another dropdown caret icon beside the dropdown (aka the upsidedown triangle) 
4. click anywhere outside of the dropdown.

## Result  
The dropdown will not close.
![Untitled](https://user-images.githubusercontent.com/33947244/77047908-e3104b80-6a08-11ea-9fdf-d6ba11a49ac0.jpg)

## Expected result  
The dropdown should close.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by jj28** [comment]
Hi any update for this bug yet?

**Comment by zdrawku** [comment]
@norikois @jj28 I've managed to reproduce the problem, this issue has been added to the current sprint

**Comment by jj28** [comment]
@zdrawku Well noted and thanks for your prompt reply. Hopefully I will get informed again once the bug has been fixed. Thank you and stay safe.

**Comment by jj28** [comment]
@zdrawku May I know that this bug fixes has been deployed? Can I check it from https://www.igniteui.com/combo/editing ?

**Comment by jj28** [comment]
@norikois Please kindly try to launch it in iPad as well. Thank you and stay safe.

**Comment by nrobakova** [comment]
Hi @jj28, thank you for pointing this. I reopened the issue and will add a new fix for iPad.

**Comment by zdrawku** [comment]
thank you for your help @jj28, the fix will be available with the upcoming ultimate release

**Comment by jj28** [comment]
> thank you for your help @jj28, the fix will be available with the upcoming 20.1 Volume Release on 15th of May

@zdrawku Thank you for your help. I have checked at my side and it finally works now by your changes! Much appreciate and thank you.
