### ISSUE TITLE
When filtered, the same records are displayed in duplicate. (via load on demand)

### ISSUE THREAD

**Issue by furugen** [IgniteUI/ignite-ui#2083]
## Description  
When filtered, the same records are displayed in duplicate. (via load on demand)

  * Use filter
 * Via load on demand

Note

 * ignite-ui version: latest
 * browser: Google Chorome

## Steps to reproduce  

1. Open the following url.
http://jsfiddle.net/tzfm3voh/1/

2. Set filter to "C"

3. Scroll down.
![video](https://user-images.githubusercontent.com/8131662/92353017-507c7980-f11a-11ea-87a6-f68ce8d953c1.gif)

## Result  
The same records are displayed in duplicate. (via load on demand)

## Expected result  
Duplicate records are not displayed.

## Attachments  
Sample
http://jsfiddle.net/tzfm3voh/1/

**Comment by dobromirts** [comment]
In the provided sample above should be used filteringType: "remote" option instead of "filterExprUrlKey" option."FilterExprUrlKey" modifies the request and will not work properly with the data source used in the example.
