### ISSUE TITLE
The formatter doesn't return the record data in the mobile view if enableVerticalRendering property is true.

### ISSUE THREAD

**Issue by cleverdog** [IgniteUI/ignite-ui#2084]
## Description  

 * ignite-ui version: 20.1
 * browser: Chrome

## Steps to reproduce  

1. Define the column including formatter.
2. Set enableVerticalRendering property to true.
3. Get the record data from formatter.

## Result  
The formatter doesn't return the record data in the mobile view. (return undefined)

[![Image from Gyazo](https://i.gyazo.com/bbe0b2224c8225312d704964de1b36f6.png)](https://gyazo.com/bbe0b2224c8225312d704964de1b36f6)
[![Image from Gyazo](https://i.gyazo.com/c175276db4dbdddb407c0120f48f070c.png)](https://gyazo.com/c175276db4dbdddb407c0120f48f070c)

## Expected result  
Return the record data properly in the mobile view.

```$('#grid').igGrid({
    columns: [
      {
        headerText: 'Company Name',
        key: 'CompanyName',
        dataType: 'string',
        formatter: (val, record) => {
          console.log('val', val)
          console.log('record', record)
        },
      },
      ...
    ],
    ...
    features: [
      {
        name: 'Responsive',
        enableVerticalRendering: true,
        reactOnContainerWidthChanges: true,
        windowWidthToRenderVertically: 750,
        propertiesColumnWidth: '40%',
        valuesColumnWidth: '60%',
        allowedColumnWidthPerType: {
          string: 300,
          number: 100,
          bool: 100,
          date: 100,
          object: 150,
        },
      },
      ...
    ],
  })```

**Comment by ChronosSF** [comment]
This bug is related to the closed-source part of Ignite UI and I am moving it to our internal system.
