### ISSUE TITLE
[igHtmlEditor] The selection from the font family dropdown is not correctly reflected to the dropdown box.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/ignite-ui#2087]
## Description  
[igHtmlEditor] The selection from the font family dropdown is not correctly reflected to the dropdown box.

 * ignite-ui version: 20.1
 * browser: IE11, Chrome, Edge (Chromium)

## Steps to reproduce  

1. Open the attached sample file.
2. Click the editor area.
3. Click the font family dropdown and select "Times New Roman".
-> The dropdown is closed. Observe what is shown in the dropdown box.
4. Click the font family dropdown and select "Arial".
-> The dropdown is closed. Observe what is shown in the dropdown box.

And so on...

## Result  
Step 3: "Meiryo" is shown.
Step 4: "MSゴシック" is shown.

And so on...

## Expected result  
Step 3: "Times New Roman" is shown.
Step 4: "Arial" is shown.
And so on...

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[CAS-33547-Sample2.zip](https://github.com/IgniteUI/ignite-ui/files/5414695/CAS-33547-Sample2.zip)

**Comment by valadzhov** [comment]
Closing this issue since it has been closed by #2094
