### ISSUE TITLE
igCombo - visibleItemsCount does not work properly if dataSource contains both half-width and full-width characters.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/ignite-ui#2119]
## Description  
visibleItemsCount does not work properly if dataSource contains both half-width and full-width characters.
IE works as expected.

 * ignite-ui version: 20.2.20.2.17
 * browser: Chrome, Edge, FireFox

## Steps to reproduce  
1. Run the attached sample in Chrome.
2. Open the drop down.

## Result  
9 items are visible.

## Expected result  
10 items are visible.

## Attachments  
[sample.zip](https://github.com/IgniteUI/ignite-ui/files/6347482/sample.zip)

**Comment by hanastasov** [comment]
The bug fix sets a fixed height for the list item container, so that the character in the value does not change this height. If the dev wants a different height, it should be set with css this way:

```html
	<style>
	.ui-igcombo-listitemholder .ui-igcombo-listitem {
		height: 2.5rem;
	}
	</style>
```

**Comment by Volen99** [comment]
The fix for this issue has been removed in [this ](https://github.com/IgniteUI/ignite-ui/pull/2201)PR. To use a fix for this one, please use the solution of the above comment :)

> The bug fix sets a fixed height for the list item container, so that the character in the value does not change this height. If the dev wants a different height, it should be set with css this way:
> 
> ```
> 	<style>
> 	.ui-igcombo-listitemholder .ui-igcombo-listitem {
> 		height: 2.5rem;
> 	}
> 	</style>
> ```
