### ISSUE TITLE
The versions of ignite-ui npm packages in npmjs and packages.infragistics.com don't match

### ISSUE THREAD

**Issue by VMihalkov** [IgniteUI/ignite-ui#2156]
## Description  
The versions of ignite-ui npm package in https://www.npmjs.com/package/ignite-ui and https://packages.infragistics.com/feeds/js-licensed/@infragistics/ignite-ui-full/versions don't match.

## Steps to reproduce  

1. Go to https://packages.infragistics.com/feeds/js-licensed/@infragistics/ignite-ui-full/versions and check latest 20.2 version. It is 20.2.35
2. Go to https://www.npmjs.com/package/ignite-ui and check latest 20.2 version. It is 20.2.30

These are actually the same packages (exluding the licensed/trial difference). It's just that the package in npmjs is wrong version. It is version 20.2.30, because this is the version of the installer containing the same ignite-ui nuget package for the latest service release.

## Result  
The versions don't match, because the versions in npmjs are actually the installer versions for the release. 

## Expected result  
The versions should match. In npmjs the versions should be the real versions of the ignite-ui package, not the installer versions.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
When making Releases or Service Releases this is already doing - the versions in npm and proget are the same. It seems that for 20.2 this wasn't done properly.
