### ISSUE TITLE
JSHint error on build

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/ignite-ui#247]
Related to https://github.com/jshint/jshint/issues/3013
For some reason our -W100 ignore is not being respected in [infragistics.util.js#L3564](https://github.com/IgniteUI/ignite-ui/blob/aef7a8e4d87233a8fba827b15ed81aaebabd8a9c/src/js/modules/infragistics.util.js#L3564)

Might be resolved if we try to manually add and use 2.9.2 instead.

**Comment by kdinev** [comment]
@damyanpetev Let's move JSHint to npm and fix the version at 2.9.2.

**Comment by damyanpetev** [comment]
@kdinev better yet testing with shrinkwrap. Worked on a local install so will see in the log if it does indeed install the fixed version.

**Comment by kdinev** [comment]
It's fixed now. Closing the issue.
