### ISSUE TITLE
Exception when setting min/max date

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui#27]
'Cannot read property dpDiv of undefined' is thrown after setting MinDate/maxDate at runtime and selecting a date.

**Comment by kdinev** [comment]
@dafo there is no unit test added for this one. Include one please.

**Comment by Marina-L-Stoyanova** [comment]
Closes #28

**Comment by kdinev** [comment]
@dafo Build hid this, but the JSHint is failing. Fix it please.
