### ISSUE TITLE
[igCheckBoxEditor] Check misaligned when combined with grid/tree

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/ignite-ui#322]
1. Open [igCheckBox-tick-css.zip](https://github.com/IgniteUI/ignite-ui/files/467675/igCheckBox-tick-css.zip)
2. Inspect the selected checkbox

**Result:** Only an edge of the check is barely visible - the check icon is positioned outside the box.
**Expected:** The icon should be properly positioned. 

This is only reproducible when other controls' (shared and tree) styling added in the mix as those contain the global checkbox class rules, which should definitely not be in the tree at the very least. Also a **regression** compared to 16.1.

**Comment by damyanpetev** [comment]
Alright after some digging I saw _the same margin rules on the icon being overridden multiple times_ and more importantly - shared css was overriding the tree rule which should **not** be happening at all. While the issue above stands, this raises questions for a potential new one:

Since the order of styles is defined in the loader I suspected that might be broken, but it turned out this can be reproduced with simple file list like so:
[igCheckBox-tick-css-alt.zip](https://github.com/IgniteUI/ignite-ui/files/467712/igCheckBox-tick-css-alt.zip)
So the only recent change tracked back to https://github.com/IgniteUI/ignite-ui/commit/21280f34dc5647b0e65b5c8a7b31df5467a9477d - and indeed resetting to state before this commit cleared the issue and reproducible with its changes applied. It looks like the imports are forcing multiple instances of the same style, as visible in the rule hierarchy and FF Style Editor:
![image](https://cloud.githubusercontent.com/assets/3198469/18443062/f1664d10-791b-11e6-99f6-89e660ed8976.png)

<a href="https://cloud.githubusercontent.com/assets/3198469/18442573/f849ccd0-7919-11e6-80a0-0bc47b2e362b.png" target="_blank"><img src="https://cloud.githubusercontent.com/assets/3198469/18442573/f849ccd0-7919-11e6-80a0-0bc47b2e362b.png" alt="image"height="300"></a>

So far I can only say that using CSS `@import` for modular dependency management not suitable for shared files at all, as it doesn't behave like you'd expect (it doesn't load a file, but each import is a style reevaluation) and that destroys the hierarchy order files depend on.
Besides messing with the 'cascading' part of CSS, this might also be causing some overhead as well.

@alexkartavov I see what you wanted to do, but the imports seem like a no-go to me. Any chance of using the combined structure file or some other method of modular loading instead?

// cc @sdimchevski @desig9stein @kdinev @bazal4o

**Comment by kdinev** [comment]
@damyanpetev I believe the last PR by @alexkartavov fixes the issue. Could you please test?

**Comment by damyanpetev** [comment]
Yes, I can verify that after the latest changes the rules are no longer re-applied a few times. :+1: 

The check icon is still slightly misaligned from the tree style (original issue), but it's visible and I've already talked to @desig9stein to make sure the tree overrides only its own icon.

**Comment by IvayloG** [comment]
@kdinev 
I have tested this with the above samples, as well as additionally including igTree and igGrid and could not find an issue. It seems fine.
