### ISSUE TITLE
Localization of igTree

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/ignite-ui#353]
There are some changes in the description of the options/methods/events of the igTree that need to be localized.

Here are the commits with the changes:
7f7b5e01cf29bfbc257c393e2b1c84a7005828c6

**Comment by ig-ealbert** [comment]
If the only changes in the commit referenced by Mariana were code snippets being removed, then there is nothing to do here.  The commit was too large to view.  The other commits are from July and they have already been incorporated through the regular update process.
If all that is true, this can be closed.
