### ISSUE TITLE
Localization of igVideoPlayer

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/ignite-ui#356]
There are some changes in the description of the options/methods/events of the igVideoPlayer that need to be localized.

Here are the commits with the changes:
cf6cd329b17dd12cc234e2a772a78598c135c132

**Comment by IvayloG** [comment]
Several method descriptions to be localized.
Here are the commits with the changes:
c243e5b3a425fcf835ac99794ea3aed69c4d21f7

**Comment by ig-ealbert** [comment]
Done for commit cf6cd32.  Changeset 594279.
Still need to do the method description changes.

**Comment by ig-ealbert** [comment]
Changeset 594531 covers IvalyoG's changes.
Please close - this is completed.
