### ISSUE TITLE
Error is thrown: Uncaught RangeError: Invalid array length in igTileManager, when click on new tab and resize the window

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/ignite-ui#357]
In _getContainerWidthNoScroll function in infragistics.ui.layoutmanager.js, this line of code return NaN:
widthNoScroll = parseInt(window.getComputedStyle(this.element[ 0 ]).width, 10);

**Comment by kdinev** [comment]
@Aleksandyr Is this reproducible in a sample? Which one?

**Comment by kdinev** [comment]
Ok, I found it! It's in the leading-tile sample.

https://github.com/IgniteUI/ignite-ui/blob/master/demos/tile-manager/leading-tile.html
