### ISSUE TITLE
Localization of igRating

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/ignite-ui#358]
There are some changes in the description of the options/methods/events of the igRating that need to be localized.

Here are the commits with the changes:
af87669915b60da24d7ff6a79d3343e9ef3feb69

**Comment by IvayloG** [comment]
Several method descriptions to be localized.
Here are the commits with the changes:
c243e5b3a425fcf835ac99794ea3aed69c4d21f7

**Comment by ig-ealbert** [comment]
Changeset 594538.  This can be closed.
FYI I went with the CDATA approach for adding internal links, as that is what is built out to the XML files in the build.
