### ISSUE TITLE
igMaskEditor - inputMask allows entering characters/letters

### ISSUE THREAD

**Issue by agicheva** [IgniteUI/ignite-ui#364]
**Steps to reproduce**

Create a sample with the following code:
`$("#maskEditor").igMaskEditor({
                        inputMask: ">00"
                    });`

Try to enter a character.

**Actual result:**
You are allowed to enter character/letters.

**Expected result:**
You should not be able to enter character/letters.

**Comment by bazal4o** [comment]
Verified by @agicheva
