### ISSUE TITLE
igMaskEditor - inputMask disapearing value

### ISSUE THREAD

**Issue by agicheva** [IgniteUI/ignite-ui#365]
**Steps to reproduce**

Create a sample with the following code:
`$("#maskEditor").igMaskEditor({
                        inputMask: ">LLL00"
                    });`
Enter value. Focus out.

**Actual result**
The value is disappearing from the editor.

**Expected result**
The value is supposed to be in the editor.

**Comment by bazal4o** [comment]
Verified by @agicheva
