### ISSUE TITLE
Improve the API descriptions for methods

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/ignite-ui#370]
These descriptions could be more meaningful, and consistent across widgets. The following is a list of the widgets to be checked for such possible improvements.

- [x]  igCheckboxEditor
- [x]  igCurrencyEditor
- [x]  igDateEditor
- [x]  igDatePicker
- [x]  igMaskEditor
- [x]  igNumericEditor
- [x]  igPercentEditor
- [x]  igTextEditor
- [x]  igBaseEditor
- [x]  igTree
- [x]  igNotifier
- [x]  igValidator
- [x]  igVideoPlayer
- [x]  igRating
- [x]  igDialog

**Comment by kdinev** [comment]
@IvayloG Should #371 close this issue?
