### ISSUE TITLE
Improve and unify the options API descriptions

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/ignite-ui#384]
These descriptions could be more meaningful, and consistent across widgets. The following is a list of the widgets to be checked for such possible improvements.

 igCheckboxEditor
 igCurrencyEditor
 igDateEditor
 igDatePicker
 igMaskEditor
 igNumericEditor
 igPercentEditor
 igTextEditor
 igBaseEditor
 igTree
 igNotifier
 igValidator
 igVideoPlayer
 igRating
 igDialog

**Comment by kdinev** [comment]
Is this one different from #370

**Comment by bazal4o** [comment]
It's more like Unify, than improve. If you review the changes most of them are related to Gets/Sets instead of Gets or Sets, Get or Set. We could just update the title of the issue if you prefer so?

**Comment by kdinev** [comment]
I would prefer that, because it looks like the same issue. I'm closing this one as duplicate and reopening #370.
