### ISSUE TITLE
Localization for the following list of widgets

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/ignite-ui#389]
The localization update is required for the following commmit:
787502f3196774d4775847a64a8f11484a26ed8b

- [x]  igCheckboxEditor
- [x]  igCurrencyEditor
- [x]  igDateEditor
- [x]  igDatePicker
- [x]  igMaskEditor
- [x]  igNumericEditor
- [x]  igPercentEditor
- [x]  igTextEditor
- [x]  igBaseEditor
- [x]  igTree
- [x]  igNotifier
- [x]  igValidator
- [x]  igVideoPlayer
- [x]  igRating
- [x]  igDialog

**Comment by kdinev** [comment]
@ig-ealbert You will be able to see in the commit, but the changes are mostly stylistic. "Gets/Sets" is added to the options, and some English grammar is corrected. This may not require any change on your end, but please check, just in case.

**Comment by ig-ealbert** [comment]
Changeset 595576 - Updated descriptions to include "Gets or sets" when necessary.  This can be closed.

**Comment by IvayloG** [comment]
@ig-ealbert 
Could you please take a look at the igRating as well and in particular:
swapDirection – Getter only
focusable- description

**Comment by ig-ealbert** [comment]
@IvayloG 
Changeset 596363.
I had initially ignored these changes because I thought that removing the "/sets" here was unintentional.  I have made the changes now.  Also made a change to "vertical" as "sets" was removed there too.
