### ISSUE TITLE
Combined files cannot be used with AMD loaders

### ISSUE THREAD

**Issue by alexkartavov** [IgniteUI/ignite-ui#396]
Since individual modules are defined as anonymous modules (similar to jquery-ui modules), combining those without any modifications presents a problem. Trying to use AMD loaders to load combined files throws an error: "multiple anonymous modules defined".
Looking at how jquery-ui overcomes this problem, they actually append AMD headers at the grunt build step - individual files get anonymous module headers, while combined version assigns each module a name that corresponds to the file name (and control name accordingly).
I've checked in comments in places where module names should be used in combined version of igniteui.
The combining task should be adjusted to uncomment those module names.
If you are going to change the module names, please let me know, I will be writing a topic on this and will need to mention those names for those customers who choose to use combined files and AMD loaders.
Thanks guys!

**Comment by damyanpetev** [comment]
@kdinev @alexkartavov Quick question though - shouldn't we remove those AMD headers and add separate ones for the combined files like the full version setup is atm? As in lob lite would depend on core lite and jQuery+UI.

The current headers don't add up at first glance (correct me if I'm wrong). Would this be a valid dependency?
```js
define( "igniteui/js/modules/infragistics.ui.editors", [
			"jquery",
			"jquery-ui",
			"./infragistics.util",
			"./infragistics.scroll",
			"./infragistics.validator"
		], factory );
```
Considering it's a relative path, there'll be no infragistics.util.js file next to the LoB file and the util module itself defines as:
```js
define( "igniteui/js/modules/infragistics.util", //....
```

**Comment by kdinev** [comment]
@damyanpetev should the issue be closed?

**Comment by damyanpetev** [comment]
@kdinev Would also revert https://github.com/IgniteUI/ignite-ui/commit/c8938510476a2b470c9e84915390a8d58a8d3b33 before closing if those comments are not going to be used anymore.
