### ISSUE TITLE
TextEditor trigger valueChanged event when clear button is clicked when the text editor is empty

### ISSUE THREAD

**Issue by agicheva** [IgniteUI/ignite-ui#447]
**Steps to reproduce:**
Create a code sample with the following code:

```
$("#firstName").igTextEditor({
                buttonType : "clear",
                valueChanged: function(evt, ui){
                    console.log("Trigger valueChanged");
                }
            });
```

Click on the clear button.

**Actual result:**
The valueChanged event is fired and in the console is logged "Trigger valueChanged".

**Expected result:**
The valueChanged event is not supposed to be fired.

**Comment:**
Test it with KnockoutJS.
http://www.igniteui.com/editors/bind-editors-with-ko

**Comment by dafo** [comment]
This is reproduced for all editors. Not only for the TextEditor.
