### ISSUE TITLE
Dates submitted throgh the igDateEditor/igDatePicker are always wrong

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui#460]
I have the following configuration:

```
@(Html.Infragistics()
.DatePickerFor(x => x.Session.StartTime)
.ID("StartHour")
.DateInputFormat("dd/MM/yyyy HH:mm")
.DateDisplayFormat("dd/MM/yyyy HH:mm")
.PlaceHolder("Select start hour")
.Width(280)
.Height(34)
.Render())
```

Actual behavior: When a submit a date, it gets displayed with a 2 hour offset (I'm in GMT+2). 

Expected behavior: I want to see the same time that I have submitted.

**Comment by kdinev** [comment]
Apparently this works if I add ` .DataMode(DateEditorDataMode.DisplayModeText)`. If this is not the current default data mode, then it should be changed.

**Comment by damyanpetev** [comment]
The DisplayModeText mode would work in this case, but display format is not necessarily required to be a valid format for the backend, so changing the default submit format (currently ISO 8601) seems a bit risky.

I see two (maybe three) issues here:
- The problem with the current toISOString, while being universally parsable, is that it's always UTC stripping the time zone info. The value is technically correct, but lacking crucial metadata and potentially also messing with usage where the timezone is not needed like this one.
- The MVC model always used the direct DateTime.toString - again no time zone to speak of, which defaults back to local time on the client. This is the actual problem causing the time shift.
- The enableUTCDates doesn't really do all ti could/should.

Ideas:
- Change the encoding of the MVC model to either similar ISO string or maybe even the MVC Json format \/Date(ticks)\/ potentially including time zone info to ensure the sameness of the value.
- However, the above might impede requirements where the client side must display the same value regardless of local zone, in which seems like a case for enableUTCDates and it could have implications on the way the date is sent from the server too. Could also dictate if the submitted value should include time zone info we can add manually (the ISO format allows for that).
- Simple text mode, kind of how it is now but with a valid universal format - think the same ISO but with DateTimeKind.Unspecified

**Comment by IG-Stanimir-Dimitrov** [comment]
Fix on hold until final design (i.e. one covering new scenarios) and the corresponding API update have been agreed.

**Comment by kdinev** [comment]
It also appears that with the configuration that I have, if I want to create a new date, then the seconds are actually not submitted as 00.

**Comment by IG-Stanimir-Dimitrov** [comment]
igDateEditor/igDatePicker will be updated to support the following matrix:

dataMode setting | Display format | VALUE |format send to server | format received from server 
---------------- | -------------- | ----- |--------------------- | ---------------------------
.date enableUTCDates: false timeOffset: 0 (new) | local | local | UTC | UTC
.localDate (new) | local | local | local | local 
.date enableUTCDates: true timeOffset ignored | UTC| Local shifted to UTC| UTC| UTC
.date enableUTCDates: false timeOffset supplied (new) | regional| Local shifted to regional| UTC| UTC

**Comment by damyanpetev** [comment]
Regarding the MVC Wrappers behavior in the same scenarios - after looking at a few default storage formats the more common case seems to be storing date+time without zone info but also intending to work with the same ambiguous value throughout. So to make it easier:

-  The wrapper will aim to serialize the value from `ToUniversalTime()` and set the offset by default.
- If any of `DateEditorDataMode.LocalDate` or EnableUTCDates (true) or `TimeOffset` are set then it'll be the unmodified ISO string (affected by [`DateTimeKind `](https://msdn.microsoft.com/en-us/library/shx7s921(v=vs.110).aspx))

Feedback is appreciated. Still considering is a provided `TimeOffset` should also enforce UTC.

@kdinev The initial date object creation could be its own separate issue.

**Comment by IG-Stanimir-Dimitrov** [comment]
igDateEditor/igDatePicker latest changes:

- <b>NB!</b> dataMode :"date" -> enforces ISO 8601 date format for the server communication

- timeOffset ->displayTimeOffet (shifts the editor display value only for dates received from the server)

- dataMode: "localDate" -> dataMode :"date", enableUTCDates: false

- enableUTCDates: true/false  -> the ISO date send to/received from the server is in UTC or goes with the time zone offset suffix

- <b>NB!</b> setDateValue method -> to be deprecated !!!

- value method -> sets/gets the display value of the editor as if it was changed directly in the editor. <b>When setting the value, it represents the date plus the offset</b>; additional offset transformation is not applied.

| Setting | Display format | VALUE | format send to server | format received from server |
| --- | --- | --- | --- | --- |
| dataMode :"date", enableUTCDates: true (applies browser time zone offset) | local | local | UTC | UTC |
| dataMode:"date", enableUTCDates: true, displayTimeOffset supplied | regional (the value of UTC+offset) | regional (the value of UTC+offset) | UTC | UTC |
| dataMode:"date", enableUTCDates: false, displayTimeOffset :0 | local | local | local | local |

**Comment by damyanpetev** [comment]
`displayTimeOffset`:
-  Should simply shift the client Date value for display purposes.
- With value of `0` takes over the current `enableUTCDates`.
- Might actually be allowed to work separate from `dataMode`?

Side note - would the above have any implications on mix/max value options?

**Comment by IG-Stanimir-Dimitrov** [comment]
1. `displayTimeOffset` should work with all `dataMode` settings 

2. `displayTimeOffset` is applied within the min/max value constrains. 

For example, if we set the editor to 2016-11-03T16:08:08.504+0200 and have 

`displayTimeOffset: 120,
maxValue: new Date(2016, 11, 03, 17, 00)` 

the editor displays 2016-11-03 17:00.

**Comment by IG-Stanimir-Dimitrov** [comment]
:bowtie: :beer:
