### ISSUE TITLE
igTileManager - fullscreen view

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui#464]
Extend the `igTileManager` to allow configuration where the maximized tile is maximized to a fullscreen view, similar to the R+ application which uses the `igTileManager`. 

The configuration should be something of the sort:

    fullscreen: true

Which will enable the tile to be fully maximized (take over the entire tile manager container), instead of taking the majority of the left/right hand side of the screen and show the remaining tiles on the other side. Minimizing the fullscreen tile should bring the tile manager back to the default minimized view.

**Comment by sstoyanovIG** [comment]
The required functionality is achievable by using splitterOptions property with the following settings:

splitterOptions: {
    enabled: true,
    collapsible: true,
    collapsed: true
}
