### ISSUE TITLE
[igDateEditor] Copy date as plain text and paste it in the editor is not setting value

### ISSUE THREAD

**Issue by agicheva** [IgniteUI/ignite-ui#504]
**Steps to reproduce:**
Create a code sample with the following code: 
```
$("#dateEditor").igDateEditor({
                      width: 280,
                      dateDisplayFormat: "dateTime",
                      dateInputFormat: "dateTime"
                  });
```
Copy this date: 11/3/2015 3:24 PM
Paste it in the editor

**Actual result:**
The value is reverted

**Expected result:**
The value of the editor to be 11/3/2015 3:24 PM

**Comment by IG-Stanimir-Dimitrov** [comment]
dateDisplayFormat: "dateTime",
    dateInputFormat: "dateTime"
           
do not seem to utilize the same dateTime pattern. The editor accepts 11/03/2015 03:24 PM or 11/_3/2015 _3:24 PM but displays 11/3/2015 3:24 PM. 

    dateInputFormat:  "M/d/yyyy h:m tt"

also does not accept 11/3/2015 3:24 PM and has a pattern identical to "MM/dd/yyyy hh:mm tt". The format must accept day, month or hour values without leading zero.
