### ISSUE TITLE
Initial date object change

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#536]
Extends issue - Dates submitted through the igDateEditor/igDatePicker are always wrong #460 

When altering already created date objects, support submitting seconds/milliseconds as 00 (i.e. reset the initial values).

**Comment by kdinev** [comment]
This would be a behavioral change and should be communicated with customers before performed. Currently the expectation of the issue is if the input format of the date does not contain, let's say seconds, the seconds to be set at 00. Correct me if I'm wrong! :)

**Comment by IG-Stanimir-Dimitrov** [comment]
Correct!
To avoid breaking current FJ implementation, the editor will default to 00 the values that are not supplied only when instantiating new date object. When changing existing dates, nothing except the altered values will be changed.
