### ISSUE TITLE
Researching modernizr touch events

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/ignite-ui#546]
In Chrome when you use modernizr in a project the igRating and igVideoplayer are in Mobile mode. 

https://github.com/modernizr/modernizr/issues/548
https://github.com/thefrontiergroup/rails-template/issues/136

**Comment by kdinev** [comment]
I believe we got rid of most references to `Modernizr.touch`, but the ones in the video player and rating are still leftover. We should just remove them.

**Comment by kdinev** [comment]
@Marina-L-Stoyanova Have references to `Modernizr.touch` been removed already? If yes, then I guess I should close the issue?

**Comment by Lipata** [comment]
With the commit above, we remove dependency on Modernizr for touch detection. But if the browser has **ontouchstart** event or **touch** class in the body, the _igRating_ and _igVideoPlayer_ will be rendered in touch mode.
