### ISSUE TITLE
Unclear and/or wrong descriptions in igToolbar API

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/ignite-ui#559]
1) http://www.igniteui.com/help/api/2016.2/ui.igtoolbar#options:allowCollapsing
2) It is not clear which is the expandButtonIcon http://www.igniteui.com/help/api/2016.2/ui.igtoolbar#options:expandButtonIcon
- better be smth like "the expand/collapse button icon"
3) http://www.igniteui.com/help/api/2016.2/ui.igtoolbar#options:isExpanded
- needs better description
4) http://www.igniteui.com/help/api/2016.2/ui.igtoolbar#events:collapsing
- desc is wrong !
5) http://www.igniteui.com/help/api/2016.2/ui.igtoolbar#events:toolbarComboOpening
- needs better desc
6) http://www.igniteui.com/help/api/2016.2/ui.igtoolbar#methods:getItem make the descriptiong consistent with the removeItem method

**Comment by kdinev** [comment]
Should I close this issue?

**Comment by IG-Stanimir-Dimitrov** [comment]
Approved by PO.
Changes were merged with pull request - fix description in igToolbarButton, igToolbar and igTileManager APIs #608
