### ISSUE TITLE
igTextEditor valueChanged event is not firing when the value in the editor is changed

### ISSUE THREAD

**Issue by igMPeterson** [IgniteUI/ignite-ui#577]
igTextEditor valueChanged event is not firing when the value in the editor is changed. Run the attached sample to see the behavior. 
[igTextEditorKnockout.zip](https://github.com/IgniteUI/ignite-ui/files/622548/igTextEditorKnockout.zip)

**Comment by TammyD79** [comment]
Is there an ETA on this?

**Comment by kdinev** [comment]
@TammyD79 We're starting a new sprint on Monday and we will put it in that sprint. ETA would be December 19th the latest.
