### ISSUE TITLE
[igDatePicker] Specify the jquery.ui.datepicker options supported by datepickerOptions

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#596]
- Update the API documentation with the specific jquery.ui.datepicker options propagated to igDatePicker
- Include them in the Ignite UI IntelliSense

**Comment by Lipata** [comment]
There is TFS task #231885 for adding jQuery DatePicker options to the Editors wrappers, so I close this issue.
