### ISSUE TITLE
Update igDateEditor/Picker Documentation

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#604]
Align the editors API documentation with the latest enableUTCDates and displayTimeOffset changes.

- [x] Editor API
- [x] Help topic
- [x] Migration guide

**Comment by Lipata** [comment]
Issues to add both documents in the help: https://github.com/IgniteUI/help-topics/issues/118, https://github.com/IgniteUI/help-topics/issues/119
