### ISSUE TITLE
The nodes in igTree are underlined

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/ignite-ui#620]
Open the following sample: [http://jsfiddle.net/gh/get/jquery/1.9.1/igniteuisamples/jsfiddle-samples/tree/master/EN/HtmlSamples/tree-control/json-binding/](http://jsfiddle.net/gh/get/jquery/1.9.1/igniteuisamples/jsfiddle-samples/tree/master/EN/HtmlSamples/tree-control/json-binding/)

The nodes in the tree are underlined and they shouldn't be. This is a regression caused by this change d00d4ea625d5f6183946134240b2294a11ed605c

**Comment by kdinev** [comment]
#627 #629
