### ISSUE TITLE
igRating selection in not working correctly in FireFox

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/ignite-ui#623]
**Create a sample with the following code:** 
```
$('#rating1').igRating(
{
    swapDirection : true
});
```
Try to vote by selecting only the last star.

**Actual result:**
All stars are marked on hover and on selection.

**Expected result:**
Only the last star should be hovered and selected as it is in the other browsers.

**_Comment:_** It is working in version FireFox 38.0

**Comment by Lipata** [comment]
You can download old version of Firefox from [here](https://ftp.mozilla.org/pub/firefox/releases/38.8.0esr/win32/en-GB/). As far as I see the fix doesn't break rating in firefox v.38. Then you can update firefox to latest.
