### ISSUE TITLE
[igNumericEditor] Default maxDecimal option

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#625]
The igNumericEditor by default applies the client-side regional decimal settings (and may return unexpected results).

Changes:

- Default maxDecimal option must not restrict the decimal length and must handle up to 15 digits out of the box.
- If a particular value is specified, it overrides the default configuration (current implementation).

**Comment by Lipata** [comment]
We had a discussion with @ChronosSF and manually setting the maxDecimals to 15 will work in this case - it will not truncate the value and also will not add 0 if the value has less than 15 numbers after the floating point. Our default maxDecimals are following this [pattern ](https://msdn.microsoft.com/en-us/library/dwhawy9k(v=vs.110).aspx) and it is not needed to change them.

**Comment by IG-Stanimir-Dimitrov** [comment]
OK I will close this issue then.

To summarize:

- min/maxDecimals apply the regional settings if set to null (default)
- Specific maxDecimals value overrides the local culture and allows the editor to accommodate larger decimal number without adding trailing zeros.
