### ISSUE TITLE
[igNumericEditor] When the value exceeds maxDecimals length, the editor directly truncates it 

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#626]
The igNumericEditor currently always truncates the decimal positions overflowing the maxDecimals length. The expected behavior for the editor is to round up to the nearest number in such cases.

Changes:

- The editor must round the value up to the max decimal precision (default behavior)

- Implement an option that sets whether values, which precision exceeds the maxDecimals length, are truncated or rounded (enhancement)

**Comment by Lipata** [comment]
@IG-Stanimir-Dimitrov I propose the name of the option to be "roundDecimalPlaces", which will have default value - true. When set to true the the editor will take the decimal places, defined in maxDecimal option, and will round the last decimal value, depending on the next one, which will be cut. For example:
value: 123.4567, with maxDecimals: 3 and roundDecimalPlaces: true will set 123.457 in the editor. If roundDecimalPlaces is false then editor will return 123.456.

**Comment by IG-Stanimir-Dimitrov** [comment]
@Lipata , I am ok with the suggested implementation.

**Comment by Lipata** [comment]
This will be added to the breaking changes document for 17.1: https://github.com/IgniteUI/help-topics/issues/128
