### ISSUE TITLE
[igDialog] Resizing button of the dialog is not rendered right when the content is bigger than the dialog

### ISSUE THREAD

**Issue by agicheva** [IgniteUI/ignite-ui#649]
**Steps to reproduce**
Open the following sample:
http://jsfiddle.net/zoe012du/3/
Resize the dialog as much as you can 

**Actual result**
The resizable button is rendered in the scroll bar.

**Expected result**
The resizable button is supposed to be rendered under the scroll bar.

**Comment by Lipata** [comment]
In order to reproduce that problem, you need to resize the dialog, so that the horizontal scroll disappears.
If you replace the igDialog with jQuery dialog, then the problem appears again ([sample](http://jsfiddle.net/zoe012du/4/)):

```
$("#dialog").dialog({
    height: "500px",
    width: "700px"
});
```
