### ISSUE TITLE
Dropping a node from one tree to another disregards the dragAndDropMode

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui#663]
When dragging and dropping between two trees, if the source tree has `dragAndDropMode: "copy"` the node is still deleted from the source tree.

Steps to reproduce:
1. Open http://jsfiddle.net/fat503ft/1/
2. Drag and drop a node from the left to the right tree

Actual result:  
The node is moved from the source to the target tree.

Expected result:  
The node is copied into the target tree.

**Comment by yog2411** [comment]
I was told that latest build link will be provided to me if i open the new ticket.

**Comment by kdinev** [comment]
@yog2411 I meant that you should open a support case in our case system. You are using the full version of our product, correct?

https://www.infragistics.com/my-account/submit-support-request

**Comment by yog2411** [comment]
yes I am  .

**Comment by kdinev** [comment]
@yog2411 Great! Please submit a case there and put a link to this issue in the case. We will provide you with the build and we'll make sure that the fix is included first.

**Comment by yog2411** [comment]
ok. Thank you so much

**Comment by kdinev** [comment]
You're welcome :)
