### ISSUE TITLE
Setup bower package

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui#7]

**Comment by damyanpetev** [comment]
Posted an issue in the bower registry as there's currently a package registered with the name (missing endpoint):
https://github.com/bower/registry/issues/207

**Comment by damyanpetev** [comment]
Package registered and installed successfully (a `bower cache clean` might be required).
Bower search hasn't updated yet, but https://libraries.io/about says the sync is daily so it might update tomorrow.
