### ISSUE TITLE
Drag and drop multiple trees 'copy' setting not working.

### ISSUE THREAD

**Issue by yog2411** [IgniteUI/ignite-ui#704]
Please refer the link below for issue.

http://stackoverflow.com/questions/41107926/drag-and-drop-ignite-ui-tree-view/41117522

dragging item removed from the source instead of preserving its original place.

**Comment by IG-Stanimir-Dimitrov** [comment]
@yog2411  this has already been reported and fixed. For reference: https://github.com/IgniteUI/ignite-ui/issues/663
