### ISSUE TITLE
Create Knockout binding for combo and editors that enables/disables them

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/ignite-ui#714]
Create binding handler, similar to the default KO ["disabled"](http://knockoutjs.com/documentation/disable-binding.html) handler, that will enables/disables the following controls - combo, editors.

The names of the bindings could be igComboDisable and igEditorEnable. We already have similar override for the default knockout "visible" binding. More about it can be found in the [following topic](http://www.igniteui.com/help/igcombo-knockoutjs-support).

The following configuration should work after the implementation - checking the checkbox should enable/disable the combo (the same is valid for the editors):

```
function ViewModel(actorsList) {
    this.isDisabled =  ko.observable(true);
}

<div id="combo" data-bind="igCombo: { width: '200' }, igComboDisable: isDisabled "></div>
<input type="checkbox" data-bind="checked: isDisabled"/>
```

**Comment by TammyD79** [comment]
Is there an ETA for this?

**Comment by Lipata** [comment]
@IG-Stanimir-Dimitrov The names of the two disabled knockout bindign handlers are - igComboDisable and igEditorDisable.

**Comment by Lipata** [comment]
Topic changes: https://github.com/IgniteUI/help-topics/issues/130
