### ISSUE TITLE
Value is not an empty string no matter that the editor is empty when setting the value to a number with too many digits

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#761]
### Description  
When we set the value to a number with too many digits after the decimal point, an exception is thrown but the value of the editor is set to that value no matter that the editor is empty.

### Steps to reproduce  

1. Initialize a numeric editor with the following options:
```
dataMode: 'double',
value: 0.000000000000000000001
```
2. Take a look at the Console
3. Get the 'value' of the editor

### Result  
The following error is shown: 
Uncaught RangeError: toFixed() digits argument must be between 0 and 20

The value method returns 1e-21

### Expected result  
What is the expected result after following the steps to reproduce?

The value method returns an empty string

**Comment by damyanpetev** [comment]
I would argue that the expected value should be 0 actually.
It's entirely another subject that `0.000000000000000000001` is indeed 1e-21 and falls completely outside of representational capabilities of `toFixed` which is limited at 20 as the error states. Such values can only work in `scientificFormat` which seems very reasonable.
Could add to the docs' Known Issues along with https://github.com/IgniteUI/ignite-ui/issues/776 and a check on the fixed formatting to prevent it from going over the limit or actually the max decimals?
