### ISSUE TITLE
[igDateEditor] Spinning up or down using the keyboard is possible even after the minValue/maxValue is reached

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#764]
### Description  
When we have set the maxValue or minValue option, spinning above the limits of those options is possible in edit mode using the keyboard UP and DOWN arrow keys.

### Steps to reproduce  

1. 
```
$('#edtr').igDateEditor({
	value: new Date(2016, 02, 26),
	maxValue: new Date(2016, 02, 27),
	buttonType: "spin"
});
```
2. Click inside the editor
3. Start spinning up using the UP arrow key

### Result  
Going outside the limits of the maxValue option is possible in edit mode when spinning with the keyboard

### Expected result  
Spinning up shouldn`t be possible after the maxValue is reached

Note: This behavior can be reproduced using the keyboard only. The spin buttons are respecting the maxValue/minValue options.

**Comment by Lipata** [comment]
In the editor the validation for boundary values, happens when the editor looses focus. That's why this is expected behavior.
