### ISSUE TITLE
[NumericEditor] Value is wrong when setting 'maxDecimals' to a value smaller than the 'minDecimals' at runtime

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#775]
### Description  
When setting the 'maxDecimals' option at runtime to a value that is smaller than the 'minDecimals', the value of the editor is not correct.  

### Steps to reproduce  

1. 
```
$('#editor').igNumericEditor({
value: 12.1234567890,
dataMode: "double",
minDecimals: 3
});
```
2. At runtime execute:
`$("#editor").igNumericEditor("option", "maxDecimals", 1)`
3. Focus the editor
4. Blur the editor

### Result  
The value is 12.100

### Expected result  
The value is 12.123

Note: 
This is only reproduced when 'maxDecimals' is set at runtime. This is not reproduced at initialization.

Scenario II: ### Steps to reproduce  

1. 
```
$('#editor').igNumericEditor({
value: 12.123,
dataMode: "double"
});
```
2. At runtime execute:
`$("#editor").igNumericEditor("option", "minDecimals", 10)`
3. Focus the editor
4. Blur the editor (The displayValue is "12.1200000000")
5. Focus the editor
6. Change the value to "12.12345"
7. Blur the editor

###Result
Value is "12.1200000000". maxDecimals is still "2" and is causing this issue.

### Expected result  
The value is 12.1234500000. When minDecimals is bigger than maxDecimals, minDecimals should has the priority.

**Comment by Marina-L-Stoyanova** [comment]
I'm closing this issue as it is already fixed.
