### ISSUE TITLE
[NumericEditor] When 'maxDecimals' is set to to 15 the last digit is not correct

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#776]
### Description  
When 'maxDecimals' is set to 15 and the last digit is bigger than 4, the last digit is wrong.

### Steps to reproduce  

1. 
```
$('#editor').igNumericEditor({
        value: 12.123456789012345,
	dataMode: "double",
	minDecimals: 15
});
```
2. Take a look at the editor`s value

### Result  
Value is 12.123456789012344

### Expected result  
Value is 12.123456789012345

**Comment by damyanpetev** [comment]
This value seems to fall outside the representation capabilities of JavaScript numbers - i.e. 12.123456789012345 literally evaluates to `12.123456789012344` in any browser console (same applies for `Number` constructor and `parseFloat`) so the value provided to the editor is exactly the result.

 JS Number are specified as binary double precision so looking at the [IEEE 754 formats](https://en.wikipedia.org/wiki/IEEE_floating_point#Basic_and_interchange_formats) the [decimal64 description](https://en.wikipedia.org/wiki/Decimal64_floating-point_format), the approximate 16 digits matches the common 15-17 digit limit usually cited. So in fixed point notation the 15 decimal places are only available based on the whole part - like 1.123456789012345 is okay, but the above and 123.12345678901235 would round one digit sooner, 1234.1234567890124 one more and so on.

Point being, that's not really a bug with the control. 
We could add a comment on the min/max decimal options that their functionality is affected by the limitations of the platform, but so is about everything else in the numeric editors.

P.S. Funny enough `toFixed()` can still produce strings exceeding the 16 digit significand but those results are mostly unpredictable and probably unexpected by users.
