### ISSUE TITLE
Setting the 'decimalSeparator' and 'negativeSign' options to equal values should not be allowed

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#778]
### Description  
Setting the 'decimalSeparator' and 'negativeSign' options results in not being able to enter fractional numbers in editing mode. 

### Steps to reproduce  

1. 
```
$('#editor').igNumericEditor({
	value: -10.76,
	negativeSign: "."
});
```
2. Focus the editor
3. Try to enter ".1.43"

### Result  
Entering the second dot sign is not possible

### Expected result  
Exception should be shown when those two options are set to the same value.

**Comment by kdinev** [comment]
I think this can be considered by-design. You can add documentation to the negative sign option that it shouldn't be set to values same as the decimal separator, etc.

**Comment by dafo** [comment]
The description is updated with #936
