### ISSUE TITLE
[NumericEditor] When trying to set a value that is below the minValue the notifier message is not correct

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#781]
### Description  
When minValue and maxValue options are set and you try to set the value to a number below the minValue, wrong notification is shown.
### Steps to reproduce  

1. 
```
$('#editor').igNumericEditor({
	minValue: 2,
	maxValue: 5
});
```
2. Focus the editor
3. Spin up using the UP arrow key

### Result  
The value is set to the minValue (2) and the following notification is shown:
"Entry exceeded the maximum value of 5 and was set to the minimum allowed one"

### Expected result  
A new message that corresponds with the described scenario should be added.

**Comment by IvayloG** [comment]
Already fixed.
