### ISSUE TITLE
Editors limited to listed values match in case insenstive manner but could get values only from the list

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#786]
### Description  
Editors with `isLimitedToListValues: true` match listed values in a case insensitive manner but could only get a specific value from the list. 

Extends https://github.com/IgniteUI/ignite-ui/issues/657
### Steps to reproduce  

E.g. I am entering a t-shirt size in an online clothes store in a dropdown igTextEditor form. If I type in 'm', the editor matches that to M and on blur (or Enter), the editor gets the value M.

**Comment by kdinev** [comment]
@IG-Stanimir-Dimitrov Did the `status: by-design` end up on this issue by accident, or is it intentional?

**Comment by IG-Stanimir-Dimitrov** [comment]
@kdinev , added it intentionally to denote that the required change is as per the existing spec but has not been implemented with the 'new' editors. Also it is not exactly a bug because this feature is completely missing from the controls.
