### ISSUE TITLE
When minDecimals/maxDecimals are set with values outside the valid boundaries, the editors must not function at all

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#793]
### Description  
When the igEditors minDecimals/maxDecimals options receive wrong values, the editors must not accept them and NOT function at all (applied to both initialization & runtime).

Relates to https://github.com/IgniteUI/ignite-ui/pull/783#pullrequestreview-19337545

**Comment by damyanpetev** [comment]
@IG-Stanimir-Dimitrov How about just initialization? Runtime invalid things are usually ignored (can error out) but rarely cause the control to self-destruct :)

**Comment by IG-Stanimir-Dimitrov** [comment]
@damyanpetev, we should be checking it only at the control initialization then.
