### ISSUE TITLE
Improve igUpload/WebUpload documentation

### ISSUE THREAD

**Issue by m-hristov** [IgniteUI/ignite-ui#796]
### Description  
We should improve documentation for WebUpload control. It would be nice to have good structured tutorial/project example using igUpload. For now links in documentation confuses our clients -some of the links are pointing to IgniteUI igUpload, others - ASP.net WebUpload.  
The documentation that was provided had issues or incomplete information.  Еxamples:
The URL [http://www.infragistics.com/help/aspnet/webupload-using-server-side-events](http://www.infragistics.com/help/aspnet/webupload-using-server-side-events) mentions the code should go in your aspx page but the header says “In web.config”. 
We have a feedback from a client - he complains about difficulties with configuring ASP.net webupload control. It takes him over a week to implement simple WebUpload control. Our current documentation confuses him -  links jumps him from the Infragistics web control to the Ignite UI control. He wants to have a simple step-by-step example of how to use this control with progress bar on a web form page.

### Steps to reproduce  @

1. Try to configure ASP.net webupload control using mainly our documentation.

### Result  
It is very difficult to configure WebUpload control using only our documentation. 

### Expected result  
It should be easy to configure WebUpload control using our documentation. We need of simple step-by-step example(s) for basic scenario(s).

### Attachments  
N/A

**Comment by mharrington622** [comment]
I had a user ask about increasing the max file size for the WebUpload and did not see [this forum post](https://www.infragistics.com/community/forums/t/64887.aspx#329039) mentioned in our documentation:

It might be nice to have this info added as well.

**Comment by mpavlinov** [comment]
We decided to drop this issue.
