### ISSUE TITLE
Notification for exceeding the minimum value of date picker is shown even if later date is selected

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#89]
**Steps to reproduce:** 
1. Create date picker:
```
$("#igDatePicker1").igDatePicker({
	minValue: new Date(2016, 06, 18)
});
```
2. Open the calendar and select '26'
3. Open the calendar again and select '25'

**Actual result:** 
Notification is shown: 'Entry exceeded the minimum value of 7/18/2016 and was set to the minimum value'

**Expected result:**
No notification is shown

**Note:**
This is regressed with commit 19f053c6f59d342a6cbccac09f89b5202188e96e

**Comment by kdinev** [comment]
@dafo go ahead and pull request a test that reproduces this.
