### ISSUE TITLE
[igCurrencyEditor] When the value is set equal to maxValue, on blur the spinUp button is active

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/ignite-ui#894]
### Description  
When the value is set equal to maxValue, on blur the spinUp button is active

### Steps to reproduce  
1. Create an editor with the following code:
```
$("#editor").igCurrencyEditor({       
         displayFactor : 1,
         maxValue: 8,
         spinDelta: 1,
         buttonType: "spin"
    });
```
2. Enter value 8 in the editor.
3. Blur the Editor.

### Result  
The spinUp button is enabled.

### Expected result  
The spinUp button should not be enabled.

I tested it with the pull request from issue #420 and it was working fine.

**Comment by Lipata** [comment]
The bug is only in 17.1

**Comment by dafo** [comment]
It seems this is regressed by #664 on January 4th, 2017

**Comment by dafo** [comment]
And the very same issue is reproduced for the Percent Editor.
