### ISSUE TITLE
igniteui.d.ts

### ISSUE THREAD

**Issue by seawerst** [IgniteUI/ignite-ui#904]
Where is the igniteui.d.ts in the repository.

**Comment by dkamburov** [comment]
There is no repository for the typings definitions. We've tried including them to the typings registry, but with no success.

We are distributing them with the IgniteUI product. You can find more info in the following pull request.
[https://github.com/typings/registry/pull/848#issuecomment-256422543](https://github.com/typings/registry/pull/848#issuecomment-256422543)

**Comment by seawerst** [comment]
Did you consider https://github.com/DefinitelyTyped/DefinitelyTyped as it is the original repository with a lot more contributors. They also automatically publish to NuGet.

**Comment by kdinev** [comment]
@seawerst We should have probably begun saying that we push our own NuGet package with the typings:

https://www.nuget.org/packages/IgniteUI.TypeScript.Definitions/

**Comment by seawerst** [comment]
It would be usefull to make public the repository reference here https://github.com/typings/registry/pull/848/files as IgniteUI/typed-igniteui so we can log issues with this file. 
Trying to use the 16.2 d.ts igniteui file you reference do not compile with TypeScript

**Comment by dkamburov** [comment]
I made a PR to DefinitelyTyped [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15419](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15419)

**Comment by kdinev** [comment]
@seawerst I agree. We should probably create a repo for that.

**Comment by seawerst** [comment]
As the comment on your PR to DefinitelyTyped mention, you should probably create your own repo under /IgniteUI

**Comment by seawerst** [comment]
Is it done yet?
With the new official release, you introduce regression bug and did not fix some of the preexisting ones I had identified.

**Comment by kdinev** [comment]
@seawerst This is done. https://www.npmjs.com/package/@types/ignite-ui

Should I close the issue?

**Comment by seawerst** [comment]
Close this one, i'll post new issues with what i have found.
