### ISSUE TITLE
[Upload] Button width style causes text to wrap incorrectly from UI perspective 

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/ignite-ui#931]
### Description  
The upload button wraps on two lines

### Steps to reproduce  

1 Go here
https://igniteui.github.io/help-samples/16.2/JA/file-upload/api-events/index.html
2 Select a file to upload

### Result  
The upload button wraps on two lines

### Expected result  
The width is adjusted to accomodate the button text

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://cloud.githubusercontent.com/assets/9548226/24791584/5ea72912-1b83-11e7-959b-e600061baac1.png)

**Comment by kdinev** [comment]
The upload supports width configuration, and the width should be configured by the developer to fit the text.
