### ISSUE TITLE
Issue with igCombo internalSelChangeSubs

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/ignite-ui#96]
```
// Fire callbacks when selection is changed from api
_callInternalSelChangeSubs: function (event) {
            var curCallback, i,
                callbacks = this._options.internalSelChangeSubs;
            **if ($.type(callbacks) === 'array') {
                ....
            }**
.......
}
```

`internalSelChangeSubs` is set to null during initialization and does not seem to update its value throughout the lifecycle or through the `_setOption` method. Therefore the code inside the if is never hit.

**Comment by kdinev** [comment]
The code is not dead, however there is a bug on this line:

https://github.com/IgniteUI/ignite-ui/blob/master/src/js/modules/infragistics.ui.combo.js#L478

The subscribers should be initialized to an empty array.
