### ISSUE TITLE
Define igDateEditor/igDatePicker spinDelta option as a set of deltas for the different time periods

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/ignite-ui#978]
### Description  
In igDateEditor and igDatePicker spinDelta option should allow defining a set of different values, each of them applied to the different time periods (minutes, hours, days). We may want the spinDelta for the minutes to be 30, while for the hours to be 1. Now the spinDelta option allows only one value that is applied to all the time periods.

**Comment by Lipata** [comment]
In addition it's important to decide the ranges for each spinDeltas. E.g. the delta for the minutes - should it take values only between 1 and 59, and if not to throw exception, or if the value is 90, just to spin the minutes with 30 and hour with 1? It should be verified that this works with the limitSpinToCurrentField option.

**Comment by IG-Stanimir-Dimitrov** [comment]
@Lipata , the spinDelta should be **number** or an **object**. 
The number would be applied to all time periods like the current version. The default would still be 1.
The object period deltas must be within the acceptable range for each specific period as follows:

| Time Period | Interval |
| ------------- |:-------------:| 
| Years | 1-10| 
| Months | 1-12| 
| Days | 1-28| 
| Hours | 1-12 | 
| Minutes | 1-60| 
| Seconds  | 1-60| 

Values outside these ranges must throw a configuration error.

**Comment by Lipata** [comment]
The name of the options - year, month, day is changed to be singular.

**Comment by kdinev** [comment]
@dafo Is this really not fixed?
