### ISSUE TITLE
Value of numeric editor is not set to 'maxValue' after pressing ENTER

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#98]
**Steps to reproduce:**
1. Initialize numeric editor, using the following code:
```
$("#numericEditor1").igNumericEditor({
  maxValue: 5
});
```

2. Focus the editor
3. Enter '9'
4. Press ENTER

**Actual result:**
The value is not changed to the maxValue - 5. Only notification is shown - 'Entry exceeded the maximum value of 5 and was set to the maximum value'

**Expected result:**
Value is set to the maxValue after pressing ENTER.

**Comment by kdinev** [comment]
@dafo Can you check that the behavior is the same with minValue?
